### Experiment with GPT 4.1-namo

In [3]:
import pandas as pd
import libs.prompts as prompts
from libs.exp_utils import classify_dataset, evaluate_experiment
from libs.openai import call_openai
from tqdm import tqdm
import json
import os

In [4]:
# Define model name
MODEL_NAME = "gpt-4.1-nano"

### Dataset load

In [5]:
# Load ground truth bug locations
with open("../../Datasets/bugLocationDappScan.json", "r") as f:
    bug_locations = json.load(f)

In [6]:
def normalize_path(path):
    if isinstance(path, str):
        return path.replace('\\', '/').replace('./', '').replace('.\\', '')
    return path

bugloc_dict = {
    normalize_path(item['file']): normalize_path(item['location'])
    for item in bug_locations
}


# Load the dataset and convert to appropriate data types
csv_path = "../../Datasets/dw.csv"
df = pd.read_csv(csv_path)
df['has_error'] = df['has_error'].astype(bool)
subset = df.reset_index(drop=True)
#subset.head()

#### Zero-shot Prompting

In [8]:
results_df = classify_dataset(subset, prompts.create_zeroshot_locate_prompt, MODEL_NAME)
precision, recall, f1, conf_matrix = evaluate_experiment(results_df)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")
results_df.head()

100it [02:42,  1.62s/it]

Precision: 91.89
Recall: 41.98
F1-Score: 57.63
Confusion Matrix:
[[16  3]
 [47 34]]

,predicted_has_error,actual_has_error,bug_type
0,1,0,Fallback function that modifies state variable...
1,0,0,NONE
2,0,0,NONE
3,0,0,NONE
4,0,0,NONE

In [9]:
results_df['file_path'] = subset['file_path']
results_df['file_name'] = subset['file_name'] 

error_cases = results_df[(results_df['predicted_has_error'] == True) & (results_df['actual_has_error'] == True)].copy()

error_cases.head()

,predicted_has_error,actual_has_error,bug_type,file_path,file_name
22,1,1,Integer Overflow / Underflow,DAppSCAN-main/DAppSCAN-source/contracts/openze...,HackerGold.sol
28,1,1,Potential Integer Overflow in getHomeFee and g...,DAppSCAN-main/DAppSCAN-source/contracts/Smartd...,BaseFeeManager.sol
30,1,1,SWC-135-Code With No Effects: The function _pr...,DAppSCAN-main/DAppSCAN-source/contracts/Iosiro...,Exchanger.sol
32,1,1,Function _mint is defined as internal and over...,DAppSCAN-main/DAppSCAN-source/contracts/PeckSh...,LuckyToken.sol
34,1,1,SWC-105-Unprotected Ether Withdrawal,DAppSCAN-main/DAppSCAN-source/contracts/consen...,Moloch.sol

In [10]:
def get_gt_category(row):
    file_path = row['file_path'].replace('DAppSCAN-main/DAppSCAN-source/', '')
    if file_path in bugloc_dict:
        location_json_path = os.path.join('../../Datasets/DAppSCAN-main/DAppSCAN-source/', bugloc_dict[file_path])
        if os.path.exists(location_json_path):
            with open(location_json_path, 'r') as f:
                location_data = json.load(f)
                swcs = location_data.get('SWCs', [])
                categories = [swc['category'] for swc in swcs if 'category' in swc]
                return categories if categories else ['Unknown']
        else:
            return ['JSON não encontrado']
    else:
        return ['Arquivo não encontrado']

In [13]:
# Roda a checagem
llm_categories = []
gt_categories = []

for idx, row in error_cases.iterrows():
    print(f"\n--- Rodando para idx {idx} ---")
    gt_cat = get_gt_category(row)

    llm_categories.append(row['bug_type'])
    gt_categories.append(gt_cat)
    print(f"File: {row['file_path']}\nLLM: {row['bug_type']}\nGT: {gt_cat}\n")

--- Rodando para idx 22 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-EtherCamp_Hacker_Gold/virtual-accelerator-2529ffe5efd5294b44f1bc89dc9a4721a7b16409/HackerGold.sol
LLM: Integer Overflow / Underflow
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-135-Code With No Effects', 'SWC-135-Code With No Effects']


--- Rodando para idx 28 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/upgradeable_contracts/BaseFeeManager.sol
LLM: Potential Integer Overflow in getHomeFee and getForeignFee functions
GT: ['SWC-110-Assert Violation']


--- Rodando para idx 30 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Synthetix Alnitak Release Smart Contract Audit/synthetix-00df930622a8ea462d15d4eccf6bc6b3d704bd21/contracts/Exchanger.sol
LLM: SWC-135-Code With No Effects: The function _processTradingRewards contains an 'if' statement that checks conditions but no effect or 'revert' if the conditions are not met. Although not strictly a vulnerability, this pattern can be confusing or indicate incomplete logic.
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 32 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-LuckyToken/Lucky-Token-c9deec551edaa18f8419bbda5fca48776f191e80/contracts/LuckyToken.sol
LLM: Function _mint is defined as internal and overrides ERC20._mint, but it is also declared as onlyOwner. Since internal functions cannot have access modifiers like onlyOwner (which is a modifier), this causes a compilation error. Additionally, the _mint function is intended to be internal, but is mistakenly decorated with onlyOwner, which is incompatible with internal functions.
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 34 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-The_LAO/moloch-4bc443f4dad60279b47978fc6987bb978d3dfc58/contracts/Moloch.sol
LLM: SWC-105-Unprotected Ether Withdrawal
GT: ['SWC-114-Transaction Order Dependence', 'SWC-105-Unprotected Ether Withdrawal', 'SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 36 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyPartialCloseLiquidate.sol
LLM: Use of unsafe arithmetic with uint256(-1); should use type(uint256).max for maximum uint value in Solidity >=0.8.0, but since version 0.6.6, this is acceptable as a negative literal converter, so no vulnerability here. However, the code uses address.safeApprove(address, uint256(-1)), which is safe in Solidity 0.6.6 but can be considered a potential issue if compiler version is updated or misused. Additionally, the use of 'now' is deprecated in Solidity 0.7.0 and above, but acceptable here due to compiler version. Beyond that, the code appears to be generally correct, assuming proper permissions and correct external contract implementations. Nonetheless, reliance on deprecated features like 'now'Id could be considered a minor vulnerability or bad practice.
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 42 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Coinfabrik-Beluga Pay (BBI) Security Audit/contractBBIT-master/bbi.sol
LLM: Unprotected Ether Withdrawal (reentrancy vulnerability in fallback function)
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-105-Unprotected Ether Withdrawal']


--- Rodando para idx 45 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Compound_Open_Oracle/open-oracle-e7a928334e5e454a88eec38e4ee1be5ee3b13f08/DelFiPrice.sol
LLM: Potential for integer division truncation in median calculation when averaging two prices
GT: ['SWC-108-State Variable Default Visibility']


--- Rodando para idx 47 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Zer0_zNS/zNS-b05e503ea1ee87dbe62b1d58426aaa518068e395/contracts/StakingController.sol
LLM: Signature verification vulnerability (lack of explicit signature scheme, potential malleability issue) and unprotected reward withdrawal (Rug-like) due to missing access control or withdrawal functions.
GT: ['SWC-105-Unprotected Ether Withdrawal', 'SWC-122-Lack of Proper Signature Verification', 'SWC-117-Signature Malleability']


--- Rodando para idx 48 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-Vault/aleswap-vault-efd3f777b2e9aaa2c635d3d0f463f1884e998112/contracts/strategies/Warden/StrategyWardenLP.sol
LLM: Inconsistent use of delegatecall vs call: The code uses SafeERC20 for token transfers but does not explicitly use delegatecall. Additionally, the initializer functions rely on OpenZeppelin's upgradeable pattern but do not enforce the correct initializers for parent contracts, which might lead to misconfigurations. Moreover, the use of block.timestamp (or now) for deadlines in swap and addLiquidity functions can be manipulated within certain bounds, but since it defaults to now, it's generally acceptable in this context. A notable point is the use of uint256(-1), which is a common pattern for unlimited allowances but can lead to approval issues if tokens have restrictions. Overall, no immediate critical bug is identified, but potential concerns include lack of slippage control in swaps and allowance management, which could be exploited. Since no explicit critical vulnerabilities like reentrancy or integer overflow/underflow (beyond safeMath) are apparent, the primary consideration is design robustness.
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 50 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Frax/Pools/FraxPool.sol
LLM: Unchecked return value from transfer and transferFrom calls (e.g., collateral_token.transferFrom, collateral_token.transfer, FXS.transfer). The code does not verify the success of these calls, potentially leading to failed token transfers going unnoticed and causing inconsistencies.
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 53 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Misc_AMOs/InvestorAMO_V2.sol
LLM: L263: Unchecked call return value in giveCollatBack function
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 55 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-COSMOS_Fundraiser/fundraiser-lib-693cf3f32e9fd679216372876dda86fa57a3277e/src/truffle/contracts/Fundraiser.sol
LLM: Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-102-Outdated Compiler Version', 'SWC-107-Reentrancy']


--- Rodando para idx 56 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Timvi Governance Token and Distribution DAO Smart Contract Audit/Timvi-Governance-a6e5929701b5da5ef9980b668216410245da59b7/Distribution.sol
LLM: Use of Deprecated Solidity Functions
GT: ['SWC-111-Use of Deprecated Solidity Functions', 'SWC-111-Use of Deprecated Solidity Functions', 'SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 57 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Ackee_Blockchain-GoodGhosting/goodghosting-protocol-v1-dfda8d5d5990abb7f352bc9358ac950dce1bd677/goodghosting-protocol-v1-dfda8d5d5990abb7f352bc9358ac950dce1bd677/contracts/GoodGhosting.sol
LLM: Incorrect constructor visibility specifier for Solidity 0.6.11 (should use 'constructor' without 'public')
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 58 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-COIN98/code/code.sol
LLM: Reentrancy vulnerability in the vote() function during external call
GT: ['SWC-107-Reentrancy']


--- Rodando para idx 62 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-BNPL/BNPL-0ee587a081668dcab166a3a275b8a6c4794ead4d/contracts/BankingNode.sol
LLM: Uninitialized variable 'unbondingShares' is never explicitly set to 0 upon user initiation, but the function 'unstake' assumes it is properly initialized. This could lead to incorrect unbonding calculations if the default value is not zeroed or if multiple unbonding processes are not properly managed. Moreover, the logic in 'unstake' relies on safe division assuming unbondingShares[msg.sender] > 0, but in the case where the user unbonds more than their shares, or if the mapping isn't correctly reset, there could be inconsistencies. Additionally, there's a logical bug in the calculation of 'getNextPayment' where the interest-only and amortized calculations may not be correctly implemented, leading to incorrect payment amounts, but that's more a correctness issue than a vulnerability.
GT: ['SWC-114-Transaction Order Dependence', 'SWC-107-Reentrancy']


--- Rodando para idx 65 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-CryptoBatz Smart Contract/crypto-batz-contracts-07ee07dd442c34622798f1ee5b73ef8ff59cef48/contracts/CryptoBatz.sol
LLM: Potential Reentrancy Vulnerability in buyPublic method due to external call before state update
GT: ['SWC-116-Block values as a proxy for time']


--- Rodando para idx 66 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Fuel_Token/FUEL-Contracts-3717b751bb2fa57ae300776a93ee4d7d7beb2c07/FuelToken.sol
LLM: Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 67 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Fuel_Token/FUEL-Contracts-3717b751bb2fa57ae300776a93ee4d7d7beb2c07/FuelCrowdfund.sol
LLM: Unchecked Call Return Value in closeCrowdfund (Line 84)
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 69 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/staking_pools/MixinStakingPool.sol
LLM: SWC-112 - Delegatecall to Untrusted Callee
GT: ['SWC-112-Delegatecall to Untrusted Callee']


--- Rodando para idx 70 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/libs/LibFixedMath.sol
LLM: Incorrect overflow check in private _add function
GT: ['SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 74 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-origin/origin-4b31657825523962434c6d4e4c61feb0bb1ee518/origin-contracts/contracts/marketplace/v00/Marketplace.sol
LLM: SWC-105-Transaction-Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 79 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsulting-GSPI Club-project3/code/spi_staking.sol
LLM: Incorrect require condition in unstake: require(user.amount >= 0) is always true; should be require(user.amount > 0).
GT: ['SWC-103-Floating Pragma', 'SWC-135-Code With No Effects']


--- Rodando para idx 84 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Callisto_Network-IDEX Security Audit/idex-4a05eb28e570e9820066474ff2adc924ce7a27bd/MyToken.sol
LLM: Use of 'throw' for error handling (deprecated in later Solidity versions) and missing 'view' or 'pure' modifiers on some functions
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 85 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-Spherium/code/code.sol
LLM: Integer Overflow/Underflow Vulnerability
GT: ['SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 87 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-BitSliced Smart Contract/SLICED-Smart-Contract-d243190125c15dbe9628a844f764a5d0e484f3a0/Sliced.sol
LLM: Possible Integer Overflow/Underflow risk in sendTokens() due to multiplication before division, and potential issues with lastTransferDate update logic
GT: ['SWC-116-Block values as a proxy for time']


--- Rodando para idx 92 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FujiProtocol/fuji-protocol-933ea57b11889d87744efa23e95c90b7bf589402/contracts/FujiVault.sol
LLM: SWC-106-Unprotected SELFDESTRUCT Instruction: L23 - L673
GT: ['SWC-106-Unprotected SELFDESTRUCT Instruction', 'SWC-112-Delegatecall to Untrusted Callee', 'SWC-112-Delegatecall to Untrusted Callee', 'SWC-112-Delegatecall to Untrusted Callee', 'SWC-112-Delegatecall to Untrusted Callee']


--- Rodando para idx 93 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FujiProtocol/fuji-protocol-933ea57b11889d87744efa23e95c90b7bf589402/contracts/abstracts/vault/VaultBaseUpgradeable.sol
LLM: Use of delegatecall with untrusted target, potential for code execution if _provider is malicious or compromised.
GT: ['SWC-112-Delegatecall to Untrusted Callee']


--- Rodando para idx 94 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/ImmuneBytes-SportsIcon-Audit Report/SportsIcon-Vesting-8a26ed5c3a52b7a4d1b22a38b40dd80783ecc6a3/SportsIconPrivateVesting.sol
LLM: Unchecked return value of token.transfer in claim() function (SWC-104)
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 95 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Hacken-Tenderize/tender-core-1fd606141625171fe792045ae9233890262d2d62/contracts/tenderizer/integrations/graph/Graph.sol
LLM: Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 96 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Hacken-Tenderize/tender-core-1fd606141625171fe792045ae9233890262d2d62/contracts/tenderizer/integrations/matic/Matic.sol
LLM: Unchecked Call Return Value
GT: ['SWC-135-Code With No Effects', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 98 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Polymath/polymath-token-672fabe081e8f90ea025252d92c2eb247d60010e/contracts/PolyDistribution.sol
LLM: Potential integer overflow in airdropTokens when summing airdropped amount (SWC-101). Additionally, the constructor uses an unsafe new PolyToken(this) which may be problematic if PolyToken has a non-standard constructor. Also, the code does not verify the success of POLY.transfer calls in some places, which could lead to state inconsistency.
GT: ['SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 99 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/SlowMist-eden-network Smart Contract Security Audit Report/governance-e7b55f6e3f9c0d3ede7fd8bb39ae4fa7a4f4e79e/contracts/DistributorGovernance.sol
LLM: Potential DoS (Denial of Service) vulnerability in delegateBatch function due to unvalidated external call loop potentially consuming excessive gas or failing on invalid input. Additionally, the constructor assumes that the length of _blockProducers and _collectors match, but does not check for overflows or invalid data beyond length equality. Furthermore, the rewardSchedule variable is set via a bytes parameter but no validation or access control is enforced besides onlyGov, which might be acceptable depending on context. Overall, the code is relatively safe, but the delegateBatch loop could be exploited with a large input array to cause DoS
GT: ['SWC-113-DoS with Failed Call']

In [14]:
comparison_results = []

for bug_pred, gt_cat in tqdm(zip(error_cases['bug_type'], gt_categories), total=len(gt_categories)):
    prompt = prompts.create_zeroshot_error_comparison_prompt(bug_pred, gt_cat)
    response = call_openai(MODEL_NAME, prompt)
    try:
        result = json.loads(response)
        same_error = int(result.get("same_error", False))
    except Exception as e:
        print("Erro ao interpretar resposta da LLM:", e)
        same_error = 0 

    comparison_results.append({'actual_has_error': 1, 'predicted_has_error': same_error})

comparison_df = pd.DataFrame(comparison_results)

precision, recall, f1, conf_matrix = evaluate_experiment(comparison_df)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")

  0%|          | 0/34 [00:00<?, ?it/s]

100%|██████████| 34/34 [00:30<00:00,  1.11it/s]

Precision: 100.00
Recall: 52.94
F1-Score: 69.23
Confusion Matrix:
[[ 0  0]
 [16 18]]

#### Zero-shot CoT Prompting

In [15]:
results_df = classify_dataset(subset, prompts.create_zeroshot_cot_locate_prompt, MODEL_NAME)
precision, recall, f1, conf_matrix = evaluate_experiment(results_df)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")
results_df.head()

100it [05:33,  3.33s/it]

Precision: 86.67
Recall: 32.10
F1-Score: 46.85
Confusion Matrix:
[[15  4]
 [55 26]]

   predicted_has_error  actual_has_error bug_type
0                    0                 0     NONE
1                    0                 0     NONE
2                    0                 0     NONE
3                    0                 0     NONE
4                    0                 0     NONE

In [16]:
results_df['file_path'] = subset['file_path']
results_df['file_name'] = subset['file_name'] 

error_cases = results_df[(results_df['predicted_has_error'] == True) & (results_df['actual_has_error'] == True)].copy()

error_cases.head()

,predicted_has_error,actual_has_error,bug_type,file_path,file_name
22,1,1,Integer Overflow and Underflow,DAppSCAN-main/DAppSCAN-source/contracts/openze...,HackerGold.sol
29,1,1,Reentrancy vulnerability,DAppSCAN-main/DAppSCAN-source/contracts/Smartd...,HomeBridgeErcToErc.sol
34,1,1,Unprotected Ether Withdrawal (SWC-105),DAppSCAN-main/DAppSCAN-source/contracts/consen...,Moloch.sol
35,1,1,Potential Reentrancy / Approval Race Condition,DAppSCAN-main/DAppSCAN-source/contracts/Inspex...,SpookySwapStrategyWithdrawMinimizeTrading.sol
38,1,1,Arithmetic Overflow/Underflow in Calculation,DAppSCAN-main/DAppSCAN-source/contracts/Inspex...,SpookySwapStrategyAddBaseTokenOnly.sol

In [17]:
def get_gt_category(row):
    file_path = row['file_path'].replace('DAppSCAN-main/DAppSCAN-source/', '')
    if file_path in bugloc_dict:
        location_json_path = os.path.join('../../Datasets/DAppSCAN-main/DAppSCAN-source/', bugloc_dict[file_path])
        if os.path.exists(location_json_path):
            with open(location_json_path, 'r') as f:
                location_data = json.load(f)
                swcs = location_data.get('SWCs', [])
                categories = [swc['category'] for swc in swcs if 'category' in swc]
                return categories if categories else ['Unknown']
        else:
            return ['JSON não encontrado']
    else:
        return ['Arquivo não encontrado']

In [19]:
# Roda a checagem
llm_categories = []
gt_categories = []

for idx, row in error_cases.iterrows():
    print(f"\n--- Rodando para idx {idx} ---")
    gt_cat = get_gt_category(row)

    llm_categories.append(row['bug_type'])
    gt_categories.append(gt_cat)
    print(f"File: {row['file_path']}\nLLM: {row['bug_type']}\nGT: {gt_cat}\n")

--- Rodando para idx 22 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-EtherCamp_Hacker_Gold/virtual-accelerator-2529ffe5efd5294b44f1bc89dc9a4721a7b16409/HackerGold.sol
LLM: Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-135-Code With No Effects', 'SWC-135-Code With No Effects']


--- Rodando para idx 29 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
LLM: Reentrancy vulnerability
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 34 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-The_LAO/moloch-4bc443f4dad60279b47978fc6987bb978d3dfc58/contracts/Moloch.sol
LLM: Unprotected Ether Withdrawal (SWC-105)
GT: ['SWC-114-Transaction Order Dependence', 'SWC-105-Unprotected Ether Withdrawal', 'SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 35 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyWithdrawMinimizeTrading.sol
LLM: Potential Reentrancy / Approval Race Condition
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 38 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyAddBaseTokenOnly.sol
LLM: Arithmetic Overflow/Underflow in Calculation
GT: ['SWC-102-Outdated Compiler Version', 'SWC-114-Transaction Order Dependence']


--- Rodando para idx 39 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyAddTwoSidesOptimal.sol
LLM: Outdated Compiler Version and Deprecated SafeMath Usage
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 42 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Coinfabrik-Beluga Pay (BBI) Security Audit/contractBBIT-master/bbi.sol
LLM: Reentrancy vulnerability
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-105-Unprotected Ether Withdrawal']


--- Rodando para idx 45 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Compound_Open_Oracle/open-oracle-e7a928334e5e454a88eec38e4ee1be5ee3b13f08/DelFiPrice.sol
LLM: Integer Overflow/Underflow (potential in ratio calculation)
GT: ['SWC-108-State Variable Default Visibility']


--- Rodando para idx 47 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Zer0_zNS/zNS-b05e503ea1ee87dbe62b1d58426aaa518068e395/contracts/StakingController.sol
LLM: Unprotected Ether/Token Transfer (SWC-105)
GT: ['SWC-105-Unprotected Ether Withdrawal', 'SWC-122-Lack of Proper Signature Verification', 'SWC-117-Signature Malleability']


--- Rodando para idx 51 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Curve/CurveAMO.sol
LLM: Potential reentrancy vulnerability in giveCollatBack function
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 53 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Misc_AMOs/InvestorAMO_V2.sol
LLM: Unchecked return value (SWC-104)
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 55 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-COSMOS_Fundraiser/fundraiser-lib-693cf3f32e9fd679216372876dda86fa57a3277e/src/truffle/contracts/Fundraiser.sol
LLM: Reentrancy vulnerability
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-102-Outdated Compiler Version', 'SWC-107-Reentrancy']


--- Rodando para idx 58 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-COIN98/code/code.sol
LLM: Reentrancy vulnerability in vote()
GT: ['SWC-107-Reentrancy']


--- Rodando para idx 66 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Fuel_Token/FUEL-Contracts-3717b751bb2fa57ae300776a93ee4d7d7beb2c07/FuelToken.sol
LLM: SWC-114: Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 67 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Fuel_Token/FUEL-Contracts-3717b751bb2fa57ae300776a93ee4d7d7beb2c07/FuelCrowdfund.sol
LLM: Unchecked Return Value
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 74 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-origin/origin-4b31657825523962434c6d4e4c61feb0bb1ee518/origin-contracts/contracts/marketplace/v00/Marketplace.sol
LLM: Potential Reentrancy Vulnerability in refundBuyer and paySeller functions
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 75 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Hacken-TrustSwap-V1/code/StakingPool.sol
LLM: Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 85 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-Spherium/code/code.sol
LLM: Integer Overflow/Underflow
GT: ['SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 86 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Hacken-CGU/CGUToken0x747D74dB20cc422F39ab54EDB2A3Ce21f3C98AF1/contracts/CGUToken.sol
LLM: Enhancement / Potential Security Issue: Missing return in transferFrom function
GT: ['SWC-100-Function Default Visibility', 'SWC-100-Function Default Visibility']


--- Rodando para idx 88 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Endaoment/endaoment-contracts-f60aa253d3d869ad6460877f23e6092acb313add/Fund.sol
LLM: Reentrancy Vulnerability
GT: ['SWC-107-Reentrancy']


--- Rodando para idx 92 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FujiProtocol/fuji-protocol-933ea57b11889d87744efa23e95c90b7bf589402/contracts/FujiVault.sol
LLM: Delegatecall to Untrusted Callee
GT: ['SWC-106-Unprotected SELFDESTRUCT Instruction', 'SWC-112-Delegatecall to Untrusted Callee', 'SWC-112-Delegatecall to Untrusted Callee', 'SWC-112-Delegatecall to Untrusted Callee', 'SWC-112-Delegatecall to Untrusted Callee']


--- Rodando para idx 93 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FujiProtocol/fuji-protocol-933ea57b11889d87744efa23e95c90b7bf589402/contracts/abstracts/vault/VaultBaseUpgradeable.sol
LLM: Delegatecall to Untrusted Callee
GT: ['SWC-112-Delegatecall to Untrusted Callee']


--- Rodando para idx 94 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/ImmuneBytes-SportsIcon-Audit Report/SportsIcon-Vesting-8a26ed5c3a52b7a4d1b22a38b40dd80783ecc6a3/SportsIconPrivateVesting.sol
LLM: Unchecked Return Value
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 95 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Hacken-Tenderize/tender-core-1fd606141625171fe792045ae9233890262d2d62/contracts/tenderizer/integrations/graph/Graph.sol
LLM: Incorrect Function Call Name
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 96 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Hacken-Tenderize/tender-core-1fd606141625171fe792045ae9233890262d2d62/contracts/tenderizer/integrations/matic/Matic.sol
LLM: Unchecked Call Return Value
GT: ['SWC-135-Code With No Effects', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 98 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Polymath/polymath-token-672fabe081e8f90ea025252d92c2eb247d60010e/contracts/PolyDistribution.sol
LLM: Integer Overflow / Underflow (SWC-101)
GT: ['SWC-101-Integer Overflow and Underflow']

In [20]:
comparison_results = []

for bug_pred, gt_cat in tqdm(zip(error_cases['bug_type'], gt_categories), total=len(gt_categories)):
    prompt = prompts.create_zeroshot_error_comparison_prompt(bug_pred, gt_cat)
    response = call_openai(MODEL_NAME, prompt)
    try:
        result = json.loads(response)
        same_error = int(result.get("same_error", False))
    except Exception as e:
        print("Erro ao interpretar resposta da LLM:", e)
        same_error = 0 

    comparison_results.append({'actual_has_error': 1, 'predicted_has_error': same_error})

comparison_df = pd.DataFrame(comparison_results)

precision, recall, f1, conf_matrix = evaluate_experiment(comparison_df)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")

100%|██████████| 26/26 [00:26<00:00,  1.01s/it]

Precision: 100.00
Recall: 61.54
F1-Score: 76.19
Confusion Matrix:
[[ 0  0]
 [10 16]]

#### Zero-shot ToT Prompting

In [10]:
results_df = classify_dataset(subset, prompts.create_zeroshot_tot_locate_prompt, MODEL_NAME)
precision, recall, f1, conf_matrix = evaluate_experiment(results_df)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")
results_df.head()

400it [1:16:32, 11.48s/it]

Precision: 58.93
Recall: 99.00
F1-Score: 73.88
Confusion Matrix:
[[ 62 138]
 [  2 198]]

,predicted_has_error,actual_has_error,bug_type,location
0,1,0,Unprotected fallback function allowing arbitra...,48-51
1,1,0,Arbitrary Storage Write Vulnerability,64-68
2,1,0,Multiple inheritance initialization conflict,94-95
3,1,0,Incorrect bitmask usage and missing access con...,26-34
4,1,0,Lack of access control allowing arbitrary stor...,"18-21, 28-31, 38-41, 48-51, 58-61, 68-71"

In [11]:
results_df['file_path'] = subset['file_path']
results_df['file_name'] = subset['file_name'] 

error_cases = results_df[(results_df['predicted_has_error'] == True) & (results_df['actual_has_error'] == True)].copy()

error_cases.head()

,predicted_has_error,actual_has_error,bug_type,location,file_path,file_name
200,1,1,NONE,NONE,DAppSCAN-main/DAppSCAN-source/contracts/QuillA...,ERC20Permit.sol
201,1,1,Floating Pragma,3,DAppSCAN-main/DAppSCAN-source/contracts/Chains...,AccessControl.sol
202,1,1,Floating Pragma and Outdated Compiler Version,4,DAppSCAN-main/DAppSCAN-source/contracts/Chains...,AccessControl.sol
203,1,1,Integer Overflow/Underflow,"30, 90",DAppSCAN-main/DAppSCAN-source/contracts/openze...,HackerGold.sol
204,1,1,Integer Underflow leading to logical error,121-124,DAppSCAN-main/DAppSCAN-source/contracts/PeckSh...,UserConfiguration.sol

In [12]:
def get_gt_category(row):
    file_path = row['file_path'].replace('DAppSCAN-main/DAppSCAN-source/', '')
    if file_path in bugloc_dict:
        location_json_path = os.path.join('../../Datasets/DAppSCAN-main/DAppSCAN-source/', bugloc_dict[file_path])
        if os.path.exists(location_json_path):
            with open(location_json_path, 'r') as f:
                location_data = json.load(f)
                swcs = location_data.get('SWCs', [])
                categories = [swc['category'] for swc in swcs if 'category' in swc]
                return categories if categories else ['Unknown']
        else:
            return ['JSON não encontrado']
    else:
        return ['Arquivo não encontrado']

In [13]:
# Roda a checagem
llm_categories = []
gt_categories = []

for idx, row in error_cases.iterrows():
    print(f"\n--- Rodando para idx {idx} ---")
    gt_cat = get_gt_category(row)

    llm_categories.append(row['bug_type'])
    llm_categories.append(row['location'])  # Assuming 'bug_type' is the LLM's prediction
    gt_categories.append(gt_cat)
    print(f"File: {row['file_path']}\nLLM: {row['bug_type']}\nGT: {gt_cat}\n")

    print("LOCATION: LINE - ", row['location'])
#print("LLM Categories:", llm_categories, "GT Categories:", gt_categories)

--- Rodando para idx 200 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-1inch-token/1inch-token-99fd056f91005ca521a02a005f7bcd8f77e06afc/contracts/ERC20Permit.sol
LLM: NONE
GT: ['SWC-114-Transaction Order Dependence']

LOCATION: LINE -  NONE

--- Rodando para idx 201 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsulting-SWAPP Protocol-project1/openzeppelin-contracts-3.3.0/contracts/access/AccessControl.sol
LLM: Floating Pragma
GT: ['SWC-103-Floating Pragma']

LOCATION: LINE -  3

--- Rodando para idx 202 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsulting-GSPI Club-project2/openzeppelin-contracts-3.2.0/contracts/access/AccessControl.sol
LLM: Floating Pragma and Outdated Compiler Version
GT: ['SWC-103-Floating Pragma', 'SWC-102-Outdated Compiler Version']

LOCATION: LINE -  4

--- Rodando para idx 203 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-EtherCamp_Hacker_Gold/virtual-accelerator-2529ffe5efd5294b44f1bc89dc9a4721a7b16409/HackerGold.sol
LLM: Integer Overflow/Underflow
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-135-Code With No Effects', 'SWC-135-Code With No Effects']

LOCATION: LINE -  30, 90

--- Rodando para idx 204 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-AaveV3/code/aave-v3-core-14f6148e21b477d78347db6a1603039c9559e275/contracts/protocol/libraries/configuration/UserConfiguration.sol
LLM: Integer Underflow leading to logical error
GT: ['SWC-101-Integer Overflow and Underflow']

LOCATION: LINE -  121-124

--- Rodando para idx 205 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-AaveV3/code/aave-v3-core-14f6148e21b477d78347db6a1603039c9559e275/contracts/protocol/libraries/logic/ReserveLogic.sol
LLM: Division by zero
GT: ['SWC-131-Presence of unused variables']

LOCATION: LINE -  111-119

--- Rodando para idx 206 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-AaveV3/code/aave-v3-core-14f6148e21b477d78347db6a1603039c9559e275/contracts/protocol/libraries/logic/FlashLoanLogic.sol
LLM: Reentrancy vulnerability (SWC-107)
GT: ['SWC-107-Reentrancy']

LOCATION: LINE -  182-240

--- Rodando para idx 207 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-GrowthDeFi WHEAT/wheat-v1-core-8360ac0a537589bb974e8a5a169bb3e7c95d2857/contracts/Exchange.sol
LLM: Reentrancy
GT: ['SWC-107-Reentrancy']

LOCATION: LINE -  80-90

--- Rodando para idx 208 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/ERC677.sol
LLM: Outdated Compiler Version (SWC-102)
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  2

--- Rodando para idx 209 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/upgradeable_contracts/BaseFeeManager.sol
LLM: 1) Lack of access control on fee setters leading to potential division by zero in calculateFee
2) Predictable randomness vulnerability in random function (SWC-110)
GT: ['SWC-110-Assert Violation']

LOCATION: LINE -  Lines 14-23 (calculateFee), 25-33 (setHomeFee, setForeignFee), 48-50 (random)

--- Rodando para idx 210 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
LLM: Missing return statement in functions declared to return a value
GT: ['SWC-135-Code With No Effects']

LOCATION: LINE -  Lines 90-114 (function _initialize), Lines 70-88 (function _rewardableInitialize)

--- Rodando para idx 211 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Synthetix Alnitak Release Smart Contract Audit/synthetix-00df930622a8ea462d15d4eccf6bc6b3d704bd21/contracts/Exchanger.sol
LLM: NONE
GT: ['SWC-135-Code With No Effects']

LOCATION: LINE -  NONE

--- Rodando para idx 212 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Synthetix Alnitak Release Smart Contract Audit/synthetix-00df930622a8ea462d15d4eccf6bc6b3d704bd21/contracts/Synthetix.sol
LLM: Use of tx.origin for authorization (SWC-115)
GT: ['SWC-115-Authorization through tx.origin']

LOCATION: LINE -  96

--- Rodando para idx 213 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-LuckyToken/Lucky-Token-c9deec551edaa18f8419bbda5fca48776f191e80/contracts/LuckyToken.sol
LLM: Misuse of access control modifier on internal function causing potential reverts (SWC-135 Code With No Effects)
GT: ['SWC-135-Code With No Effects']

LOCATION: LINE -  54

--- Rodando para idx 214 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/New_Alchemy_Security_Audit-The Abyss DAICO Smart Contract Audit (New)/abyss-daico-21d6232a802cd966b86629cadeac0b7f3816f719/Crowdsale.sol
LLM: Reentrancy vulnerability
GT: ['SWC-116-Block values as a proxy for time']

LOCATION: LINE -  Lines 230-243, 280-320

--- Rodando para idx 215 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-The_LAO/moloch-4bc443f4dad60279b47978fc6987bb978d3dfc58/contracts/Moloch.sol
LLM: Transaction Order Dependence (Front-running)
GT: ['SWC-114-Transaction Order Dependence', 'SWC-105-Unprotected Ether Withdrawal', 'SWC-101-Integer Overflow and Underflow']

LOCATION: LINE -  266-305

--- Rodando para idx 216 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyWithdrawMinimizeTrading.sol
LLM: Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  15

--- Rodando para idx 217 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyPartialCloseLiquidate.sol
LLM: Outdated Compiler Version (SWC-102)
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  15

--- Rodando para idx 218 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyPartialCloseMinimizeTrading.sol
LLM: Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  15

--- Rodando para idx 219 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyAddBaseTokenOnly.sol
LLM: Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version', 'SWC-114-Transaction Order Dependence']

LOCATION: LINE -  14

--- Rodando para idx 220 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyAddTwoSidesOptimal.sol
LLM: Outdated Compiler Version (SWC-102)
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  15

--- Rodando para idx 221 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyLiquidate.sol
LLM: Front-running / Sandwich Attack due to missing slippage protection
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  54

--- Rodando para idx 222 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/workers/spookyswap/SpookyWorker03.sol
LLM: Lack of Slippage Protection (Front-running / Sandwich Attack Vulnerability)
GT: ['SWC-114-Transaction Order Dependence']

LOCATION: LINE -  Lines 220, 260

--- Rodando para idx 223 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Coinfabrik-Beluga Pay (BBI) Security Audit/contractBBIT-master/bbi.sol
LLM: Logic bug in transfer restriction condition
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-105-Unprotected Ether Withdrawal']

LOCATION: LINE -  169-174, 182-187

--- Rodando para idx 224 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-88mph/88mph-contracts-76cd9d1fc45e65f5d0f686621fe6af85c40aa140/contracts/rewards/xMPH.sol
LLM: Unchecked Call Return Value (SWC-104)
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  178, 196, 212

--- Rodando para idx 225 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Compound_Open_Oracle/open-oracle-e7a928334e5e454a88eec38e4ee1be5ee3b13f08/OpenOracleData.sol
LLM: Code with No Effects / Incomplete Code with Placeholders
GT: ['SWC-135-Code With No Effects']

LOCATION: LINE -  9-28

--- Rodando para idx 226 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Compound_Open_Oracle/open-oracle-e7a928334e5e454a88eec38e4ee1be5ee3b13f08/DelFiPrice.sol
LLM: Logic flaw in input array length validation; State variable default visibility
GT: ['SWC-108-State Variable Default Visibility']

LOCATION: LINE -  19,22,25,56-74

--- Rodando para idx 227 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Zer0_zNS/zNS-b05e503ea1ee87dbe62b1d58426aaa518068e395/contracts/Registrar.sol
LLM: Missing event declarations and missing _setTokenURI function
GT: ['SWC-135-Code With No Effects', 'SWC-135-Code With No Effects']

LOCATION: LINE -  Lines 51-67 (events emitted in addController/removeController), Lines 90-100 (setDomainMetadataUri calling _setTokenURI)

--- Rodando para idx 228 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Zer0_zNS/zNS-b05e503ea1ee87dbe62b1d58426aaa518068e395/contracts/StakingController.sol
LLM: Lack of Proper Signature Verification and Replay Vulnerability
GT: ['SWC-105-Unprotected Ether Withdrawal', 'SWC-122-Lack of Proper Signature Verification', 'SWC-117-Signature Malleability']

LOCATION: LINE -  92-101, 121-153, 135

--- Rodando para idx 229 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-Vault/aleswap-vault-efd3f777b2e9aaa2c635d3d0f463f1884e998112/contracts/strategies/Warden/StrategyWardenLP.sol
LLM: Transaction Order Dependence (front-running) and tx.origin usage vulnerability
GT: ['SWC-114-Transaction Order Dependence']

LOCATION: LINE -  129-136, 81-102

--- Rodando para idx 230 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Frax/Frax.sol
LLM: Denial of Service (DoS) with Block Gas Limit due to unbounded array growth; Uninitialized oracle addresses leading to potential runtime failures
GT: ['SWC-128-DoS With Block Gas Limit']

LOCATION: LINE -  252-257, 130-150 (oracle usage lines)

--- Rodando para idx 231 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Frax/Pools/FraxPool.sol
LLM: Unchecked Return Value (SWC-104)
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  204, 250, 366, 370, 401

--- Rodando para idx 232 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Curve/CurveAMO.sol
LLM: Unchecked Call Return Value (SWC-104) and Logic Error in ERC20 Approval
GT: ['SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  371, 345

--- Rodando para idx 233 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Curve/CurveAMO_V2.sol
LLM: Logic error: incorrect ERC20 approval and missing return statement in metapoolWithdrawAtCurRatio; unnecessary approve call in burnFXS
GT: ['SWC-101-Integer Overflow and Underflow']

LOCATION: LINE -  Lines 370-393 (metapoolWithdrawAtCurRatio), Lines 400-406 (burnFXS), Line 242 (minor overflow risk)

--- Rodando para idx 234 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Misc_AMOs/InvestorAMO_V2.sol
LLM: Unchecked Return Value (SWC-104)
GT: ['SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  263

--- Rodando para idx 235 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Coinbae-Barnbridge_Staking_Pool/Staking0xb0Fa2BeEe3Cf36a7Ac7E99B885b48538Ab364853/contracts/Staking.sol
LLM: 1. Floating Pragma Vulnerability (SWC-103)
2. Denial of Emergency Withdraw due to shared lastWithdrawEpochId mapping (Design Flaw)
3. Inconsistent state update in emergencyWithdraw leading to accounting errors (Logic Bug)
4. Missing return value checks on ERC20 token transfers (ERC20 Compliance Issue)
GT: ['SWC-103-Floating Pragma']

LOCATION: LINE -  2 (pragma), 152-176 (emergencyWithdraw), 97-140 (withdraw), 59-95 (deposit), 177-182 (token.transfer calls without return checks)

--- Rodando para idx 236 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-COSMOS_Fundraiser/fundraiser-lib-693cf3f32e9fd679216372876dda86fa57a3277e/src/truffle/contracts/Fundraiser.sol
LLM: Integer Overflow, Reentrancy, Outdated Compiler Version
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-102-Outdated Compiler Version', 'SWC-107-Reentrancy']

LOCATION: LINE -  9, 93-101, 128

--- Rodando para idx 237 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Timvi Governance Token and Distribution DAO Smart Contract Audit/Timvi-Governance-a6e5929701b5da5ef9980b668216410245da59b7/Distribution.sol
LLM: Use of Deprecated Solidity Functions
GT: ['SWC-111-Use of Deprecated Solidity Functions', 'SWC-111-Use of Deprecated Solidity Functions', 'SWC-101-Integer Overflow and Underflow']

LOCATION: LINE -  73, 130-135, 139

--- Rodando para idx 238 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Ackee_Blockchain-GoodGhosting/goodghosting-protocol-v1-dfda8d5d5990abb7f352bc9358ac950dce1bd677/goodghosting-protocol-v1-dfda8d5d5990abb7f352bc9358ac950dce1bd677/contracts/GoodGhosting.sol
LLM: Reentrancy vulnerability
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  Lines 193-230 (withdraw function), Lines 157-182 (earlyWithdraw function)

--- Rodando para idx 239 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-COIN98/code/code.sol
LLM: Reentrancy vulnerability; Missing 'emit' keyword for events
GT: ['SWC-107-Reentrancy']

LOCATION: LINE -  Lines 176-193 (vote function)

--- Rodando para idx 240 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-Boomstarter Smart Contracts Security Review/boomstarter-ico-ec2d28f0c3243b8f782cbd44522b5a9ca0fc22a8/contracts/BoomstarterICO.sol
LLM: Integer Underflow in for loop causing infinite loop (getPrice function), Incorrect Inheritance Order
GT: ['SWC-125-Incorrect Inheritance Order', 'SWC-135-Code With No Effects']

LOCATION: LINE -  Lines 193-199 (getPrice function), Line 13 (contract declaration)

--- Rodando para idx 241 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Solidified-2Key [14.10.2019]/contracts-de171eb80e9ce1c6566a5d782f0a0549ab0151ad/contracts/2key/singleton-contracts/TwoKeyMaintainersRegistry.sol
LLM: Unprotected Initialization (Uninitialized Proxy) and DoS with Block Gas Limit
GT: ['SWC-128-DoS With Block Gas Limit', 'SWC-128-DoS With Block Gas Limit']

LOCATION: LINE -  Lines 27-51 (setInitialParams), Lines 79-87 (addMaintainers), Lines 98-107 (removeMaintainers)

--- Rodando para idx 242 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/SlowMist-wault.finance(WUSD) Smart Contract Security Audit Report/WUSD-91c541c2f1c0ac781ddcfb2be6a62555a5e1e8d1/WUSDMaster.sol
LLM: Transaction Order Dependence (checks-effects-interactions) and Incorrect Token Amount Calculation
GT: ['SWC-114-Transaction Order Dependence']

LOCATION: LINE -  Lines 707-726, 754-772

--- Rodando para idx 243 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-BNPL/BNPL-0ee587a081668dcab166a3a275b8a6c4794ead4d/contracts/BankingNode.sol
LLM: Reentrancy vulnerability
GT: ['SWC-114-Transaction Order Dependence', 'SWC-107-Reentrancy']

LOCATION: LINE -  615-637

--- Rodando para idx 244 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsecurity-Oasis  Multiply Smart Contracts/multiply-proxy-actions-e277ac1471a95138aaa93b39cf2c16c36c769740/contracts/multiply/MultiplyProxyActions.sol
LLM: Unchecked Call Return Value (SWC-104)
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  172

--- Rodando para idx 245 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-SpiritSwap-SpiritSwap/spiritswap-core-a23463f87fd3c7633e97fab5e8124b4499e1519e/SpiritRouter.sol
LLM: Code With No Effects
GT: ['SWC-135-Code With No Effects']

LOCATION: LINE -  274

--- Rodando para idx 246 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-CryptoBatz Smart Contract/crypto-batz-contracts-07ee07dd442c34622798f1ee5b73ef8ff59cef48/contracts/CryptoBatz.sol
LLM: Integer Underflow (Potential) in Dutch Auction Price Calculation
GT: ['SWC-116-Block values as a proxy for time']

LOCATION: LINE -  252-269

--- Rodando para idx 247 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Fuel_Token/FUEL-Contracts-3717b751bb2fa57ae300776a93ee4d7d7beb2c07/FuelToken.sol
LLM: Transaction Order Dependence (TOD) vulnerability
GT: ['SWC-114-Transaction Order Dependence']

LOCATION: LINE -  189, 204

--- Rodando para idx 248 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Fuel_Token/FUEL-Contracts-3717b751bb2fa57ae300776a93ee4d7d7beb2c07/FuelCrowdfund.sol
LLM: Unchecked Call Return Value (SWC-104)
GT: ['SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  84

--- Rodando para idx 249 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/Staking.sol
LLM: NONE
GT: ['SWC-135-Code With No Effects']

LOCATION: LINE -  NONE

--- Rodando para idx 250 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/staking_pools/MixinStakingPool.sol
LLM: Improper Access Control
GT: ['SWC-112-Delegatecall to Untrusted Callee']

LOCATION: LINE -  Lines 111-121, 130-146

--- Rodando para idx 251 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/libs/LibFixedMath.sol
LLM: Integer Overflow/Underflow due to incorrect overflow detection
GT: ['SWC-101-Integer Overflow and Underflow']

LOCATION: LINE -  361-378

--- Rodando para idx 252 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/sys/MixinScheduler.sol
LLM: Timestamp Dependency (SWC-116)
GT: ['SWC-116-Block values as a proxy for time']

LOCATION: LINE -  50, 65-79

--- Rodando para idx 254 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/dev-utils/contracts/src/LibAssetData.sol
LLM: Division by zero vulnerability
GT: ['SWC-119-Shadowing State Variables']

LOCATION: LINE -  Lines 74-95, 153-178

--- Rodando para idx 255 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-origin/origin-4b31657825523962434c6d4e4c61feb0bb1ee518/origin-contracts/contracts/marketplace/v00/Marketplace.sol

In [14]:
comparison_results = []

for bug_pred, gt_cat in tqdm(zip(error_cases['bug_type'], gt_categories), total=len(gt_categories)):
    prompt = prompts.create_zeroshot_error_comparison_prompt(bug_pred, gt_cat)
    response = call_openai(MODEL_NAME, prompt)
    try:
        result = json.loads(response)
        same_error = int(result.get("same_error", False))
    except Exception as e:
        print("Erro ao interpretar resposta da LLM:", e)
        same_error = 0 

    comparison_results.append({'actual_has_error': 1, 'predicted_has_error': same_error})

comparison_df = pd.DataFrame(comparison_results)

precision, recall, f1, conf_matrix = evaluate_experiment(comparison_df)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")

100%|██████████| 198/198 [02:57<00:00,  1.11it/s]

Precision: 100.00
Recall: 54.55
F1-Score: 70.59
Confusion Matrix:
[[  0   0]
 [ 90 108]]