### Experiment with gpt 4.o-mini

In [1]:
import pandas as pd
import libs.prompts as prompts
from libs.exp_utils import classify_dataset, evaluate_experiment
from libs.openai import call_openai
from tqdm import tqdm
import json
import os

In [2]:
# Define model name
MODEL_NAME = "gpt-4o-mini"

### Dataset load

In [3]:
# Load ground truth bug locations
with open("../../Datasets/bugLocationDappScan.json", "r") as f:
    bug_locations = json.load(f)

In [4]:
def normalize_path(path):
    return path.replace('\\', '/').replace('./', '').replace('.\\', '') 

bugloc_dict = {normalize_path(item['file']): normalize_path(item['location']) for item in bug_locations}

csv_path = "../../Datasets/dw.csv"
df = pd.read_csv(csv_path)
df['has_error'] = df['has_error'].astype(bool)
subset = df.reset_index(drop=True)
subset.head()

,dataset_name,file_path,category,file_name,has_error
0,openZeppelin,openzeppelin-contracts-master/contracts/mocks/...,contracts,RegressionImplementation.sol,False
1,openZeppelin,openzeppelin-contracts-master/contracts/mocks/...,contracts,CallReceiverMock.sol,False
2,openZeppelin,openzeppelin-contracts-master/contracts/mocks/...,contracts,InitializableMock.sol,False
3,openZeppelin,openzeppelin-contracts-master/contracts/mocks/...,contracts,AccessManagedTarget.sol,False
4,openZeppelin,openzeppelin-contracts-master/contracts/mocks/...,contracts,TransientSlotMock.sol,False

#### Zero-shot Prompting

In [ ]:
results_df = classify_dataset(subset, prompts.create_zeroshot_locate_prompt, MODEL_NAME)
precision, recall, f1, conf_matrix = evaluate_experiment(results_df)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")
results_df.head()

400it [12:23,  1.86s/it]

Precision: 56.56
Recall: 90.50
F1-Score: 69.62
Confusion Matrix:
[[ 61 139]
 [ 19 181]]

,predicted_has_error,actual_has_error,bug_type,location
0,1,0,Reentrancy vulnerability,Line 43
1,1,0,Reentrancy,NONE
2,1,0,Constructor Initialization Order Vulnerability,"Line 92, 100"
3,1,0,Storage Manipulation,20
4,0,0,NONE,NONE

In [ ]:
results_df['file_path'] = subset['file_path']
results_df['file_name'] = subset['file_name'] 

error_cases = results_df[(results_df['predicted_has_error'] == True) & (results_df['actual_has_error'] == True)].copy()

error_cases.head()

,predicted_has_error,actual_has_error,bug_type,location,file_path,file_name
200,1,1,SWC-114-Transaction Order Dependence,53,DAppSCAN-main/DAppSCAN-source/contracts/QuillA...,ERC20Permit.sol
202,1,1,SWC-103-Floating Pragma,4,DAppSCAN-main/DAppSCAN-source/contracts/Chains...,AccessControl.sol
203,1,1,SWC-101-Integer Overflow and Underflow,L90,DAppSCAN-main/DAppSCAN-source/contracts/openze...,HackerGold.sol
204,1,1,SWC-101-Integer Overflow and Underflow,122,DAppSCAN-main/DAppSCAN-source/contracts/PeckSh...,UserConfiguration.sol
206,1,1,SWC-107-Reentrancy,182-240,DAppSCAN-main/DAppSCAN-source/contracts/PeckSh...,FlashLoanLogic.sol

In [ ]:
def get_gt_category(row):
    file_path = row['file_path'].replace('DAppSCAN-main/DAppSCAN-source/', '')
    if file_path in bugloc_dict:
        location_json_path = os.path.join('../../Datasets/DAppSCAN-main/DAppSCAN-source/', bugloc_dict[file_path]) #.replace('.sol', '.json'))
        if os.path.exists(location_json_path):
            with open(location_json_path, 'r') as f:
                location_data = json.load(f)
                swcs = location_data.get('SWCs', [])
                categories = [swc['category'] for swc in swcs if 'category' in swc]
                return categories if categories else ['Unknown']
        else:
            return ['JSON não encontrado']
    else:
        return ['Arquivo não encontrado']

In [ ]:
llm_categories = []
gt_categories = []

for idx, row in error_cases.iterrows():
    print(f"\n--- Rodando para idx {idx} ---")
    gt_cat = get_gt_category(row)

    llm_categories.append(row['bug_type'])
    llm_categories.append(row['location'])
    gt_categories.append(gt_cat)
    print(f"File: {row['file_path']}\nLLM: {row['bug_type']}\nGT: {gt_cat}\n")

    print("LOCATION: LINE - ", row['location'])

--- Rodando para idx 200 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-1inch-token/1inch-token-99fd056f91005ca521a02a005f7bcd8f77e06afc/contracts/ERC20Permit.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']

LOCATION: LINE -  53

--- Rodando para idx 202 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsulting-GSPI Club-project2/openzeppelin-contracts-3.2.0/contracts/access/AccessControl.sol
LLM: SWC-103-Floating Pragma
GT: ['SWC-103-Floating Pragma', 'SWC-102-Outdated Compiler Version']

LOCATION: LINE -  4

--- Rodando para idx 203 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-EtherCamp_Hacker_Gold/virtual-accelerator-2529ffe5efd5294b44f1bc89dc9a4721a7b16409/HackerGold.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-135-Code With No Effects', 'SWC-135-Code With No Effects']

LOCATION: LINE -  L90

--- Rodando para idx 204 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-AaveV3/code/aave-v3-core-14f6148e21b477d78347db6a1603039c9559e275/contracts/protocol/libraries/configuration/UserConfiguration.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow']

LOCATION: LINE -  122

--- Rodando para idx 206 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-AaveV3/code/aave-v3-core-14f6148e21b477d78347db6a1603039c9559e275/contracts/protocol/libraries/logic/FlashLoanLogic.sol
LLM: SWC-107-Reentrancy
GT: ['SWC-107-Reentrancy']

LOCATION: LINE -  182-240

--- Rodando para idx 207 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-GrowthDeFi WHEAT/wheat-v1-core-8360ac0a537589bb974e8a5a169bb3e7c95d2857/contracts/Exchange.sol
LLM: SWC-107-Reentrancy
GT: ['SWC-107-Reentrancy']

LOCATION: LINE -  80-90

--- Rodando para idx 208 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/ERC677.sol
LLM: Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  2

--- Rodando para idx 209 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/upgradeable_contracts/BaseFeeManager.sol
LLM: SWC-110-Assert Violation
GT: ['SWC-110-Assert Violation']

LOCATION: LINE -  48-50

--- Rodando para idx 210 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-135-Code With No Effects']

LOCATION: LINE -  159-161

--- Rodando para idx 212 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Synthetix Alnitak Release Smart Contract Audit/synthetix-00df930622a8ea462d15d4eccf6bc6b3d704bd21/contracts/Synthetix.sol
LLM: SWC-115-Authorization through tx.origin
GT: ['SWC-115-Authorization through tx.origin']

LOCATION: LINE -  96

--- Rodando para idx 213 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-LuckyToken/Lucky-Token-c9deec551edaa18f8419bbda5fca48776f191e80/contracts/LuckyToken.sol
LLM: Ownership Vulnerability
GT: ['SWC-135-Code With No Effects']

LOCATION: LINE -  L40

--- Rodando para idx 214 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/New_Alchemy_Security_Audit-The Abyss DAICO Smart Contract Audit (New)/abyss-daico-21d6232a802cd966b86629cadeac0b7f3816f719/Crowdsale.sol
LLM: SWC-116-Block values as a proxy for time
GT: ['SWC-116-Block values as a proxy for time']

LOCATION: LINE -  148

--- Rodando para idx 215 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-The_LAO/moloch-4bc443f4dad60279b47978fc6987bb978d3dfc58/contracts/Moloch.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence', 'SWC-105-Unprotected Ether Withdrawal', 'SWC-101-Integer Overflow and Underflow']

LOCATION: LINE -  266-305

--- Rodando para idx 216 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyWithdrawMinimizeTrading.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  15

--- Rodando para idx 217 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyPartialCloseLiquidate.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  15

--- Rodando para idx 218 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyPartialCloseMinimizeTrading.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  15

--- Rodando para idx 219 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyAddBaseTokenOnly.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version', 'SWC-114-Transaction Order Dependence']

LOCATION: LINE -  14

--- Rodando para idx 220 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyAddTwoSidesOptimal.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  15

--- Rodando para idx 221 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyLiquidate.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  15

--- Rodando para idx 222 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/workers/spookyswap/SpookyWorker03.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']

LOCATION: LINE -  208-246

--- Rodando para idx 223 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Coinfabrik-Beluga Pay (BBI) Security Audit/contractBBIT-master/bbi.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-105-Unprotected Ether Withdrawal']

LOCATION: LINE -  223

--- Rodando para idx 224 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-88mph/88mph-contracts-76cd9d1fc45e65f5d0f686621fe6af85c40aa140/contracts/rewards/xMPH.sol
LLM: SWC-104-Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  178, 196, 212

--- Rodando para idx 225 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Compound_Open_Oracle/open-oracle-e7a928334e5e454a88eec38e4ee1be5ee3b13f08/OpenOracleData.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-135-Code With No Effects']

LOCATION: LINE -  9-28

--- Rodando para idx 226 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Compound_Open_Oracle/open-oracle-e7a928334e5e454a88eec38e4ee1be5ee3b13f08/DelFiPrice.sol
LLM: SWC-108-State Variable Default Visibility
GT: ['SWC-108-State Variable Default Visibility']

LOCATION: LINE -  19, 22, 25

--- Rodando para idx 228 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Zer0_zNS/zNS-b05e503ea1ee87dbe62b1d58426aaa518068e395/contracts/StakingController.sol
LLM: SWC-105-Unprotected Ether Withdrawal
GT: ['SWC-105-Unprotected Ether Withdrawal', 'SWC-122-Lack of Proper Signature Verification', 'SWC-117-Signature Malleability']

LOCATION: LINE -  92-101

--- Rodando para idx 229 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-Vault/aleswap-vault-efd3f777b2e9aaa2c635d3d0f463f1884e998112/contracts/strategies/Warden/StrategyWardenLP.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']

LOCATION: LINE -  129-136

--- Rodando para idx 230 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Frax/Frax.sol
LLM: SWC-128-DoS With Block Gas Limit
GT: ['SWC-128-DoS With Block Gas Limit']

LOCATION: LINE -  252-257

--- Rodando para idx 231 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Frax/Pools/FraxPool.sol
LLM: SWC-104-Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  204, 250, 366, 370, 401

--- Rodando para idx 232 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Curve/CurveAMO.sol
LLM: SWC-104-Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  371

--- Rodando para idx 233 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Curve/CurveAMO_V2.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow']

LOCATION: LINE -  242

--- Rodando para idx 234 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Misc_AMOs/InvestorAMO_V2.sol
LLM: SWC-104-Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  263

--- Rodando para idx 236 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-COSMOS_Fundraiser/fundraiser-lib-693cf3f32e9fd679216372876dda86fa57a3277e/src/truffle/contracts/Fundraiser.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-102-Outdated Compiler Version', 'SWC-107-Reentrancy']

LOCATION: LINE -  L95, L100, L104

--- Rodando para idx 237 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Timvi Governance Token and Distribution DAO Smart Contract Audit/Timvi-Governance-a6e5929701b5da5ef9980b668216410245da59b7/Distribution.sol
LLM: SWC-111-Use of Deprecated Solidity Functions
GT: ['SWC-111-Use of Deprecated Solidity Functions', 'SWC-111-Use of Deprecated Solidity Functions', 'SWC-101-Integer Overflow and Underflow']

LOCATION: LINE -  73, 130-135

--- Rodando para idx 238 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Ackee_Blockchain-GoodGhosting/goodghosting-protocol-v1-dfda8d5d5990abb7f352bc9358ac950dce1bd677/goodghosting-protocol-v1-dfda8d5d5990abb7f352bc9358ac950dce1bd677/contracts/GoodGhosting.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  1

--- Rodando para idx 239 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-COIN98/code/code.sol
LLM: SWC-107-Reentrancy
GT: ['SWC-107-Reentrancy']

LOCATION: LINE -  181

--- Rodando para idx 240 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-Boomstarter Smart Contracts Security Review/boomstarter-ico-ec2d28f0c3243b8f782cbd44522b5a9ca0fc22a8/contracts/BoomstarterICO.sol
LLM: SWC-125-Incorrect Inheritance Order
GT: ['SWC-125-Incorrect Inheritance Order', 'SWC-135-Code With No Effects']

LOCATION: LINE -  13

--- Rodando para idx 241 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Solidified-2Key [14.10.2019]/contracts-de171eb80e9ce1c6566a5d782f0a0549ab0151ad/contracts/2key/singleton-contracts/TwoKeyMaintainersRegistry.sol
LLM: SWC-128-DoS With Block Gas Limit
GT: ['SWC-128-DoS With Block Gas Limit', 'SWC-128-DoS With Block Gas Limit']

LOCATION: LINE -  82, 101

--- Rodando para idx 242 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/SlowMist-wault.finance(WUSD) Smart Contract Security Audit Report/WUSD-91c541c2f1c0ac781ddcfb2be6a62555a5e1e8d1/WUSDMaster.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']

LOCATION: LINE -  717-723

--- Rodando para idx 243 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-BNPL/BNPL-0ee587a081668dcab166a3a275b8a6c4794ead4d/contracts/BankingNode.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence', 'SWC-107-Reentrancy']

LOCATION: LINE -  453-470

--- Rodando para idx 244 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsecurity-Oasis  Multiply Smart Contracts/multiply-proxy-actions-e277ac1471a95138aaa93b39cf2c16c36c769740/contracts/multiply/MultiplyProxyActions.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  119

--- Rodando para idx 245 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-SpiritSwap-SpiritSwap/spiritswap-core-a23463f87fd3c7633e97fab5e8124b4499e1519e/SpiritRouter.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-135-Code With No Effects']

LOCATION: LINE -  274

--- Rodando para idx 246 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-CryptoBatz Smart Contract/crypto-batz-contracts-07ee07dd442c34622798f1ee5b73ef8ff59cef48/contracts/CryptoBatz.sol
LLM: SWC-116-Block values as a proxy for time
GT: ['SWC-116-Block values as a proxy for time']

LOCATION: LINE -  355-374

--- Rodando para idx 247 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Fuel_Token/FUEL-Contracts-3717b751bb2fa57ae300776a93ee4d7d7beb2c07/FuelToken.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']

LOCATION: LINE -  189

--- Rodando para idx 248 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Fuel_Token/FUEL-Contracts-3717b751bb2fa57ae300776a93ee4d7d7beb2c07/FuelCrowdfund.sol
LLM: SWC-104-Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  84

--- Rodando para idx 249 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/Staking.sol
LLM: Reentrancy
GT: ['SWC-135-Code With No Effects']

LOCATION: LINE -  L37-40

--- Rodando para idx 250 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/staking_pools/MixinStakingPool.sol
LLM: SWC-112-Delegatecall to Untrusted Callee
GT: ['SWC-112-Delegatecall to Untrusted Callee']

LOCATION: LINE -  1-350

--- Rodando para idx 251 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/libs/LibFixedMath.sol
LLM: Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow']

LOCATION: LINE -  361-378

--- Rodando para idx 252 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/sys/MixinScheduler.sol
LLM: SWC-116-Block values as a proxy for time
GT: ['SWC-116-Block values as a proxy for time']

LOCATION: LINE -  71

--- Rodando para idx 254 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/dev-utils/contracts/src/LibAssetData.sol
LLM: SWC-134-Integer Overflow
GT: ['SWC-119-Shadowing State Variables']

LOCATION: LINE -  Line 164

--- Rodando para idx 255 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-origin/origin-4b31657825523962434c6d4e4c61feb0bb1ee518/origin-contracts/contracts/marketplace/v00/Marketplace.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']

LOCATION: LINE -  322-333

--- Rodando para idx 256 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Hacken-TrustSwap-V1/code/StakingPool.sol
LLM: SWC-104-Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']

LOCATION: LINE -  132, 262

--- Rodando para idx 257 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-hermez/contracts-d52ed73a0c7deaf06fcb0f981e14326f95cd1b78/contracts/auction/HermezAuctionProtocol.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-114-Transaction Order Dependence', 'SWC-101-Integer Overflow and Underflow', 'SWC-101-Integer Overflow and Underflow', 'SWC-101-Integer Overflow and Underflow']

LOCATION: LINE -  273, 761-790, 802

--- Rodando para idx 258 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-hermez/contracts-d52ed73a0c7deaf06fcb0f981e14326f95cd1b78/contracts/withdrawalDelayer/WithdrawalDelayer.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']

LOCATION: LINE -  68-82

--- Rodando para idx 259 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-hermez/contracts-d52ed73a0c7deaf06fcb0f981e14326f95cd1b78/contracts/hermez/Hermez.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence', 'SWC-107-Reentrancy']

LOCATION: LINE -  170-214

--- Rodando para idx 260 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsulting-GSPI Club-project3/code/spi_staking.sol
LLM: Reentrancy Vulnerability
GT: ['SWC-103-Floating Pragma', 'SWC-135-Code With No Effects']

LOCATION: LINE -  Line 66, 78

--- Rodando para idx 261 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Paxos/simple-multisig-master/contracts/SimpleMultiSig.sol
LLM: Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']

LOCATION: LINE -  1

--- Rodando para idx 262 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-VIDB - v1.0/VIDBToken/VIDBToken.sol
LLM: SWC-116-Block values as a proxy for time
GT: ['SWC-102-Outdated Compiler Version', 'SWC-116-Block values as a proxy for time']

LOCATION: LINE -  722

--- Rodando para idx 263 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Idle_Finance/idle-tranches-d94ee7194e8cb17db13b16c338f3e780b62f5435/contracts/IdleCDO.sol
LLM: Reentrancy
GT: ['SWC-107-Reentrancy']

LOCATION: LINE -  242-258

--- Rodando para idx 264 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-Catharsis Smart Contract/catharsis-vesting-22d1bb2e234b79b10c33a4ec76ce2a98d2825364/contracts/Vesting.sol
LLM: Reentrancy vulnerability
GT: ['SWC-103-Floating Pragma', 'SWC-135-Code With No Effects']

LOCATION: LINE -  L149

--- Rodando para idx 265 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Callisto_Network-IDEX Security Audit/idex-4a05eb28e570e9820066474ff2adc924ce7a27bd/MyToken.sol
LLM: Reentrancy
GT: ['SWC-135-Code With No Effects']

LOCATION: LINE -  L45, L61

--- Rodando para idx 266 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-Spherium/code/code.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow']

LOCATION: LINE -  70, 90

--- Rodando para idx 267 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Hacken-CGU/CGUToken0x747D74dB20cc422F39ab54EDB2A3Ce21f3C98AF1/contracts/CGUToken.sol
LLM: SWC-100-Function Default Visibility
GT: ['SWC-100-Function Default Visibility', 'SWC-100-Function Default Visibility']

LOCATION: LINE -  55, 80


In [ ]:
comparison_results = []

for bug_pred, gt_cat in tqdm(zip(error_cases['bug_type'], gt_categories), total=len(gt_categories)):
    prompt = prompts.create_zeroshot_error_comparison_prompt(bug_pred, gt_cat)
    response = call_openai(MODEL_NAME, prompt)
    try:
        result = json.loads(response)
        same_error = int(result.get("same_error", False))
    except Exception as e:
        print("Erro ao interpretar resposta da LLM:", e)
        same_error = 0 

    comparison_results.append({'actual_has_error': 1, 'predicted_has_error': same_error})

comparison_df = pd.DataFrame(comparison_results)

precision, recall, f1, conf_matrix = evaluate_experiment(comparison_df)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")

100%|██████████| 181/181 [03:51<00:00,  1.28s/it]

Precision: 100.00
Recall: 81.77
F1-Score: 89.97
Confusion Matrix:
[[  0   0]
 [ 33 148]]

#### Zero-shot CoT Prompting

In [5]:
results_df = classify_dataset(subset, prompts.create_zeroshot_cot_locate_prompt, MODEL_NAME)
precision, recall, f1, conf_matrix = evaluate_experiment(results_df)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")
results_df.head()

400it [36:11,  5.43s/it]

Precision: 54.42
Recall: 98.50
F1-Score: 70.11
Confusion Matrix:
[[ 35 165]
 [  3 197]]

,predicted_has_error,actual_has_error,bug_type
0,1,0,Fallback Function Vulnerability
1,1,0,Reentrancy Vulnerability
2,1,0,Constructor Initialization Order Vulnerability
3,1,0,Storage Manipulation Vulnerability
4,1,0,Reentrancy Vulnerability

In [6]:
results_df['file_path'] = subset['file_path']
results_df['file_name'] = subset['file_name'] 

error_cases = results_df[(results_df['predicted_has_error'] == True) & (results_df['actual_has_error'] == True)].copy()

error_cases.head()

,predicted_has_error,actual_has_error,bug_type,file_path,file_name
200,1,1,SWC-114-Transaction Order Dependence,DAppSCAN-main/DAppSCAN-source/contracts/QuillA...,ERC20Permit.sol
201,1,1,SWC-103-Floating Pragma,DAppSCAN-main/DAppSCAN-source/contracts/Chains...,AccessControl.sol
202,1,1,SWC-103-Floating Pragma,DAppSCAN-main/DAppSCAN-source/contracts/Chains...,AccessControl.sol
203,1,1,SWC-135-Code With No Effects,DAppSCAN-main/DAppSCAN-source/contracts/openze...,HackerGold.sol
204,1,1,SWC-101-Integer Overflow and Underflow,DAppSCAN-main/DAppSCAN-source/contracts/PeckSh...,UserConfiguration.sol

In [7]:
def get_gt_category(row):
    file_path = row['file_path'].replace('DAppSCAN-main/DAppSCAN-source/', '')
    if file_path in bugloc_dict:
        location_json_path = os.path.join('../../Datasets/DAppSCAN-main/DAppSCAN-source/', bugloc_dict[file_path])
        if os.path.exists(location_json_path):
            with open(location_json_path, 'r') as f:
                location_data = json.load(f)
                swcs = location_data.get('SWCs', [])
                categories = [swc['category'] for swc in swcs if 'category' in swc]
                return categories if categories else ['Unknown']
        else:
            return ['JSON não encontrado']
    else:
        return ['Arquivo não encontrado']

In [9]:
# Roda a checagem
llm_categories = []
gt_categories = []

for idx, row in error_cases.iterrows():
    print(f"\n--- Rodando para idx {idx} ---")
    gt_cat = get_gt_category(row)

    llm_categories.append(row['bug_type'])
    #llm_categories.append(row['location'])  # Assuming 'bug_type' is the LLM's prediction
    gt_categories.append(gt_cat)
    print(f"File: {row['file_path']}\nLLM: {row['bug_type']}\nGT: {gt_cat}\n")

    #print("LOCATION: LINE - ", row['location'])
#print("LLM Categories:", llm_categories, "GT Categories:", gt_categories)

--- Rodando para idx 200 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-1inch-token/1inch-token-99fd056f91005ca521a02a005f7bcd8f77e06afc/contracts/ERC20Permit.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 201 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsulting-SWAPP Protocol-project1/openzeppelin-contracts-3.3.0/contracts/access/AccessControl.sol
LLM: SWC-103-Floating Pragma
GT: ['SWC-103-Floating Pragma']


--- Rodando para idx 202 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsulting-GSPI Club-project2/openzeppelin-contracts-3.2.0/contracts/access/AccessControl.sol
LLM: SWC-103-Floating Pragma
GT: ['SWC-103-Floating Pragma', 'SWC-102-Outdated Compiler Version']


--- Rodando para idx 203 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-EtherCamp_Hacker_Gold/virtual-accelerator-2529ffe5efd5294b44f1bc89dc9a4721a7b16409/HackerGold.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-135-Code With No Effects', 'SWC-135-Code With No Effects']


--- Rodando para idx 204 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-AaveV3/code/aave-v3-core-14f6148e21b477d78347db6a1603039c9559e275/contracts/protocol/libraries/configuration/UserConfiguration.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 205 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-AaveV3/code/aave-v3-core-14f6148e21b477d78347db6a1603039c9559e275/contracts/protocol/libraries/logic/ReserveLogic.sol
LLM: SWC-131-Presence of unused variables
GT: ['SWC-131-Presence of unused variables']


--- Rodando para idx 206 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-AaveV3/code/aave-v3-core-14f6148e21b477d78347db6a1603039c9559e275/contracts/protocol/libraries/logic/FlashLoanLogic.sol
LLM: SWC-107-Reentrancy
GT: ['SWC-107-Reentrancy']


--- Rodando para idx 207 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-GrowthDeFi WHEAT/wheat-v1-core-8360ac0a537589bb974e8a5a169bb3e7c95d2857/contracts/Exchange.sol
LLM: SWC-107: Reentrancy
GT: ['SWC-107-Reentrancy']


--- Rodando para idx 208 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/ERC677.sol
LLM: Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 209 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/upgradeable_contracts/BaseFeeManager.sol
LLM: SWC-110 - Assert Violation
GT: ['SWC-110-Assert Violation']


--- Rodando para idx 210 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 211 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Synthetix Alnitak Release Smart Contract Audit/synthetix-00df930622a8ea462d15d4eccf6bc6b3d704bd21/contracts/Exchanger.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 212 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Synthetix Alnitak Release Smart Contract Audit/synthetix-00df930622a8ea462d15d4eccf6bc6b3d704bd21/contracts/Synthetix.sol
LLM: SWC-115: Authorization through tx.origin
GT: ['SWC-115-Authorization through tx.origin']


--- Rodando para idx 213 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-LuckyToken/Lucky-Token-c9deec551edaa18f8419bbda5fca48776f191e80/contracts/LuckyToken.sol
LLM: Incorrect Ownership Management
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 214 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/New_Alchemy_Security_Audit-The Abyss DAICO Smart Contract Audit (New)/abyss-daico-21d6232a802cd966b86629cadeac0b7f3816f719/Crowdsale.sol
LLM: SWC-116-Block values as a proxy for time
GT: ['SWC-116-Block values as a proxy for time']


--- Rodando para idx 215 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-The_LAO/moloch-4bc443f4dad60279b47978fc6987bb978d3dfc58/contracts/Moloch.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence', 'SWC-105-Unprotected Ether Withdrawal', 'SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 216 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyWithdrawMinimizeTrading.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 217 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyPartialCloseLiquidate.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 218 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyPartialCloseMinimizeTrading.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 219 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyAddBaseTokenOnly.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version', 'SWC-114-Transaction Order Dependence']


--- Rodando para idx 220 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyAddTwoSidesOptimal.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 221 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyLiquidate.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 222 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/workers/spookyswap/SpookyWorker03.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 223 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Coinfabrik-Beluga Pay (BBI) Security Audit/contractBBIT-master/bbi.sol
LLM: SWC-105-Unprotected Ether Withdrawal
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-105-Unprotected Ether Withdrawal']


--- Rodando para idx 224 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-88mph/88mph-contracts-76cd9d1fc45e65f5d0f686621fe6af85c40aa140/contracts/rewards/xMPH.sol
LLM: SWC-104: Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 225 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Compound_Open_Oracle/open-oracle-e7a928334e5e454a88eec38e4ee1be5ee3b13f08/OpenOracleData.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 226 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Compound_Open_Oracle/open-oracle-e7a928334e5e454a88eec38e4ee1be5ee3b13f08/DelFiPrice.sol
LLM: SWC-108-State Variable Default Visibility
GT: ['SWC-108-State Variable Default Visibility']


--- Rodando para idx 227 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Zer0_zNS/zNS-b05e503ea1ee87dbe62b1d58426aaa518068e395/contracts/Registrar.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-135-Code With No Effects', 'SWC-135-Code With No Effects']


--- Rodando para idx 228 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Zer0_zNS/zNS-b05e503ea1ee87dbe62b1d58426aaa518068e395/contracts/StakingController.sol
LLM: SWC-105-Unprotected Ether Withdrawal
GT: ['SWC-105-Unprotected Ether Withdrawal', 'SWC-122-Lack of Proper Signature Verification', 'SWC-117-Signature Malleability']


--- Rodando para idx 229 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-Vault/aleswap-vault-efd3f777b2e9aaa2c635d3d0f463f1884e998112/contracts/strategies/Warden/StrategyWardenLP.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 230 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Frax/Frax.sol
LLM: SWC-128-DoS With Block Gas Limit
GT: ['SWC-128-DoS With Block Gas Limit']


--- Rodando para idx 231 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Frax/Pools/FraxPool.sol
LLM: SWC-104-Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 232 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Curve/CurveAMO.sol
LLM: SWC-104: Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 233 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Curve/CurveAMO_V2.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 234 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Misc_AMOs/InvestorAMO_V2.sol
LLM: SWC-104-Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 235 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Coinbae-Barnbridge_Staking_Pool/Staking0xb0Fa2BeEe3Cf36a7Ac7E99B885b48538Ab364853/contracts/Staking.sol
LLM: SWC-103-Floating Pragma
GT: ['SWC-103-Floating Pragma']


--- Rodando para idx 236 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-COSMOS_Fundraiser/fundraiser-lib-693cf3f32e9fd679216372876dda86fa57a3277e/src/truffle/contracts/Fundraiser.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-102-Outdated Compiler Version', 'SWC-107-Reentrancy']


--- Rodando para idx 237 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Timvi Governance Token and Distribution DAO Smart Contract Audit/Timvi-Governance-a6e5929701b5da5ef9980b668216410245da59b7/Distribution.sol
LLM: SWC-111-Use of Deprecated Solidity Functions
GT: ['SWC-111-Use of Deprecated Solidity Functions', 'SWC-111-Use of Deprecated Solidity Functions', 'SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 238 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Ackee_Blockchain-GoodGhosting/goodghosting-protocol-v1-dfda8d5d5990abb7f352bc9358ac950dce1bd677/goodghosting-protocol-v1-dfda8d5d5990abb7f352bc9358ac950dce1bd677/contracts/GoodGhosting.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 239 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-COIN98/code/code.sol
LLM: SWC-107: Reentrancy
GT: ['SWC-107-Reentrancy']


--- Rodando para idx 240 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-Boomstarter Smart Contracts Security Review/boomstarter-ico-ec2d28f0c3243b8f782cbd44522b5a9ca0fc22a8/contracts/BoomstarterICO.sol
LLM: SWC-125-Incorrect Inheritance Order
GT: ['SWC-125-Incorrect Inheritance Order', 'SWC-135-Code With No Effects']


--- Rodando para idx 241 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Solidified-2Key [14.10.2019]/contracts-de171eb80e9ce1c6566a5d782f0a0549ab0151ad/contracts/2key/singleton-contracts/TwoKeyMaintainersRegistry.sol
LLM: SWC-128-DoS With Block Gas Limit
GT: ['SWC-128-DoS With Block Gas Limit', 'SWC-128-DoS With Block Gas Limit']


--- Rodando para idx 242 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/SlowMist-wault.finance(WUSD) Smart Contract Security Audit Report/WUSD-91c541c2f1c0ac781ddcfb2be6a62555a5e1e8d1/WUSDMaster.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 243 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-BNPL/BNPL-0ee587a081668dcab166a3a275b8a6c4794ead4d/contracts/BankingNode.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence', 'SWC-107-Reentrancy']


--- Rodando para idx 244 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsecurity-Oasis  Multiply Smart Contracts/multiply-proxy-actions-e277ac1471a95138aaa93b39cf2c16c36c769740/contracts/multiply/MultiplyProxyActions.sol
LLM: SWC-104-Unchecked Call Return Value
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 245 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-SpiritSwap-SpiritSwap/spiritswap-core-a23463f87fd3c7633e97fab5e8124b4499e1519e/SpiritRouter.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 246 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-CryptoBatz Smart Contract/crypto-batz-contracts-07ee07dd442c34622798f1ee5b73ef8ff59cef48/contracts/CryptoBatz.sol
LLM: SWC-116-Block values as a proxy for time
GT: ['SWC-116-Block values as a proxy for time']


--- Rodando para idx 247 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Fuel_Token/FUEL-Contracts-3717b751bb2fa57ae300776a93ee4d7d7beb2c07/FuelToken.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 248 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Fuel_Token/FUEL-Contracts-3717b751bb2fa57ae300776a93ee4d7d7beb2c07/FuelCrowdfund.sol
LLM: SWC-104-Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 249 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/Staking.sol
LLM: Reentrancy Vulnerability
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 250 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/staking_pools/MixinStakingPool.sol
LLM: SWC-112-Delegatecall to Untrusted Callee
GT: ['SWC-112-Delegatecall to Untrusted Callee']


--- Rodando para idx 251 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/libs/LibFixedMath.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 252 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/sys/MixinScheduler.sol
LLM: SWC-116-Block values as a proxy for time
GT: ['SWC-116-Block values as a proxy for time']


--- Rodando para idx 253 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/interfaces/IStructs.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-135-Code With No Effects', 'SWC-135-Code With No Effects']


--- Rodando para idx 254 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/dev-utils/contracts/src/LibAssetData.sol
LLM: SWC-119-Shadowing State Variables
GT: ['SWC-119-Shadowing State Variables']


--- Rodando para idx 255 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-origin/origin-4b31657825523962434c6d4e4c61feb0bb1ee518/origin-contracts/contracts/marketplace/v00/Marketplace.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 256 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Hacken-TrustSwap-V1/code/StakingPool.sol
LLM: SWC-104: Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 257 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-hermez/contracts-d52ed73a0c7deaf06fcb0f981e14326f95cd1b78/contracts/auction/HermezAuctionProtocol.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-114-Transaction Order Dependence', 'SWC-101-Integer Overflow and Underflow', 'SWC-101-Integer Overflow and Underflow', 'SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 258 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-hermez/contracts-d52ed73a0c7deaf06fcb0f981e14326f95cd1b78/contracts/withdrawalDelayer/WithdrawalDelayer.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 259 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-hermez/contracts-d52ed73a0c7deaf06fcb0f981e14326f95cd1b78/contracts/hermez/Hermez.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence', 'SWC-107-Reentrancy']


--- Rodando para idx 260 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsulting-GSPI Club-project3/code/spi_staking.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-103-Floating Pragma', 'SWC-135-Code With No Effects']


--- Rodando para idx 261 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Paxos/simple-multisig-master/contracts/SimpleMultiSig.sol
LLM: SWC-102: Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 262 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-VIDB - v1.0/VIDBToken/VIDBToken.sol
LLM: SWC-102-Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version', 'SWC-116-Block values as a proxy for time']


--- Rodando para idx 263 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Idle_Finance/idle-tranches-d94ee7194e8cb17db13b16c338f3e780b62f5435/contracts/IdleCDO.sol
LLM: Reentrancy Vulnerability
GT: ['SWC-107-Reentrancy']


--- Rodando para idx 264 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-Catharsis Smart Contract/catharsis-vesting-22d1bb2e234b79b10c33a4ec76ce2a98d2825364/contracts/Vesting.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-103-Floating Pragma', 'SWC-135-Code With No Effects']


--- Rodando para idx 265 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Callisto_Network-IDEX Security Audit/idex-4a05eb28e570e9820066474ff2adc924ce7a27bd/MyToken.sol
LLM: SWC-135: Code With No Effects
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 266 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-Spherium/code/code.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 267 ---

In [10]:
comparison_results = []

for bug_pred, gt_cat in tqdm(zip(error_cases['bug_type'], gt_categories), total=len(gt_categories)):
    prompt = prompts.create_zeroshot_error_comparison_prompt(bug_pred, gt_cat)
    response = call_openai(MODEL_NAME, prompt)
    try:
        result = json.loads(response)
        same_error = int(result.get("same_error", False))
    except Exception as e:
        print("Erro ao interpretar resposta da LLM:", e)
        same_error = 0 

    comparison_results.append({'actual_has_error': 1, 'predicted_has_error': same_error})

comparison_df = pd.DataFrame(comparison_results)

precision, recall, f1, conf_matrix = evaluate_experiment(comparison_df)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")

100%|██████████| 197/197 [04:09<00:00,  1.26s/it]

Precision: 100.00
Recall: 80.20
F1-Score: 89.01
Confusion Matrix:
[[  0   0]
 [ 39 158]]

#### Zero-shot ToT Prompting

In [11]:
results_df = classify_dataset(subset, prompts.create_zeroshot_tot_locate_prompt, MODEL_NAME)
precision, recall, f1, conf_matrix = evaluate_experiment(results_df)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")
results_df.head()

248it [36:55, 25.78s/it]

Attempt 1 failed: Request timed out.
extract_json_from_text: recebeu texto vazio ou None!
Texto com erro: None

249it [37:56, 36.50s/it]

Attempt 1 failed: Request timed out.
extract_json_from_text: recebeu texto vazio ou None!
Texto com erro: None

400it [1:06:11,  9.93s/it]

Precision: 53.95
Recall: 100.00
F1-Score: 70.09
Confusion Matrix:
[[ 31 169]
 [  0 198]]

,predicted_has_error,actual_has_error,bug_type
0,1,0,Shadowing and State Modification in Fallback
1,1,0,"Revert without reason, Infinite loop"
2,1,0,Initializer misuse and inheritance conflict
3,1,0,Storage manipulation vulnerability
4,1,0,"Reentrancy, Lack of Access Control, Informatio..."

In [12]:
results_df['file_path'] = subset['file_path']
results_df['file_name'] = subset['file_name'] 

error_cases = results_df[(results_df['predicted_has_error'] == True) & (results_df['actual_has_error'] == True)].copy()

error_cases.head()

,predicted_has_error,actual_has_error,bug_type,file_path,file_name
200,1,1,SWC-114-Transaction Order Dependence,DAppSCAN-main/DAppSCAN-source/contracts/QuillA...,ERC20Permit.sol
201,1,1,"Floating Pragma, Access Control Vulnerability",DAppSCAN-main/DAppSCAN-source/contracts/Chains...,AccessControl.sol
202,1,1,Floating Pragma and Outdated Compiler Version,DAppSCAN-main/DAppSCAN-source/contracts/Chains...,AccessControl.sol
203,1,1,Integer Overflow and Underflow,DAppSCAN-main/DAppSCAN-source/contracts/openze...,HackerGold.sol
204,1,1,SWC-101-Integer Overflow and Underflow,DAppSCAN-main/DAppSCAN-source/contracts/PeckSh...,UserConfiguration.sol

In [13]:
def get_gt_category(row):
    file_path = row['file_path'].replace('DAppSCAN-main/DAppSCAN-source/', '')
    if file_path in bugloc_dict:
        location_json_path = os.path.join('../../Datasets/DAppSCAN-main/DAppSCAN-source/', bugloc_dict[file_path])
        if os.path.exists(location_json_path):
            with open(location_json_path, 'r') as f:
                location_data = json.load(f)
                swcs = location_data.get('SWCs', [])
                categories = [swc['category'] for swc in swcs if 'category' in swc]
                return categories if categories else ['Unknown']
        else:
            return ['JSON não encontrado']
    else:
        return ['Arquivo não encontrado']

In [14]:
# Roda a checagem
llm_categories = []
gt_categories = []

for idx, row in error_cases.iterrows():
    print(f"\n--- Rodando para idx {idx} ---")
    gt_cat = get_gt_category(row)

    llm_categories.append(row['bug_type'])
    #llm_categories.append(row['location'])  # Assuming 'bug_type' is the LLM's prediction
    gt_categories.append(gt_cat)
    print(f"File: {row['file_path']}\nLLM: {row['bug_type']}\nGT: {gt_cat}\n")

    #print("LOCATION: LINE - ", row['location'])
#print("LLM Categories:", llm_categories, "GT Categories:", gt_categories)

--- Rodando para idx 200 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-1inch-token/1inch-token-99fd056f91005ca521a02a005f7bcd8f77e06afc/contracts/ERC20Permit.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 201 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsulting-SWAPP Protocol-project1/openzeppelin-contracts-3.3.0/contracts/access/AccessControl.sol
LLM: Floating Pragma, Access Control Vulnerability
GT: ['SWC-103-Floating Pragma']


--- Rodando para idx 202 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsulting-GSPI Club-project2/openzeppelin-contracts-3.2.0/contracts/access/AccessControl.sol
LLM: Floating Pragma and Outdated Compiler Version
GT: ['SWC-103-Floating Pragma', 'SWC-102-Outdated Compiler Version']


--- Rodando para idx 203 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-EtherCamp_Hacker_Gold/virtual-accelerator-2529ffe5efd5294b44f1bc89dc9a4721a7b16409/HackerGold.sol
LLM: Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-135-Code With No Effects', 'SWC-135-Code With No Effects']


--- Rodando para idx 204 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-AaveV3/code/aave-v3-core-14f6148e21b477d78347db6a1603039c9559e275/contracts/protocol/libraries/configuration/UserConfiguration.sol
LLM: SWC-101-Integer Overflow and Underflow
GT: ['SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 205 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-AaveV3/code/aave-v3-core-14f6148e21b477d78347db6a1603039c9559e275/contracts/protocol/libraries/logic/ReserveLogic.sol
LLM: SWC-131-Presence of unused variables
GT: ['SWC-131-Presence of unused variables']


--- Rodando para idx 206 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-AaveV3/code/aave-v3-core-14f6148e21b477d78347db6a1603039c9559e275/contracts/protocol/libraries/logic/FlashLoanLogic.sol
LLM: SWC-107-Reentrancy
GT: ['SWC-107-Reentrancy']


--- Rodando para idx 207 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-GrowthDeFi WHEAT/wheat-v1-core-8360ac0a537589bb974e8a5a169bb3e7c95d2857/contracts/Exchange.sol
LLM: Reentrancy
GT: ['SWC-107-Reentrancy']


--- Rodando para idx 208 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/ERC677.sol
LLM: Outdated Compiler Version, Missing Function Implementation
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 209 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/upgradeable_contracts/BaseFeeManager.sol
LLM: Integer Division by Zero, Randomness Manipulation
GT: ['SWC-110-Assert Violation']


--- Rodando para idx 210 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-TokenBridge (by POA Network) Smart Contracts Security Analysis/tokenbridge-contracts-bbb97a63c900f03a902d0e82358abac3b294e4d9/contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
LLM: Multiple vulnerabilities including improper checks and potential reentrancy
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 211 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Synthetix Alnitak Release Smart Contract Audit/synthetix-00df930622a8ea462d15d4eccf6bc6b3d704bd21/contracts/Exchanger.sol
LLM: Reentrancy vulnerability, potential manipulation of exchange rates
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 212 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Synthetix Alnitak Release Smart Contract Audit/synthetix-00df930622a8ea462d15d4eccf6bc6b3d704bd21/contracts/Synthetix.sol
LLM: SWC-115 - Authorization through tx.origin
GT: ['SWC-115-Authorization through tx.origin']


--- Rodando para idx 213 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-LuckyToken/Lucky-Token-c9deec551edaa18f8419bbda5fca48776f191e80/contracts/LuckyToken.sol
LLM: Ownership and minting logic vulnerability
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 214 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/New_Alchemy_Security_Audit-The Abyss DAICO Smart Contract Audit (New)/abyss-daico-21d6232a802cd966b86629cadeac0b7f3816f719/Crowdsale.sol
LLM: SWC-116-Block values as a proxy for time
GT: ['SWC-116-Block values as a proxy for time']


--- Rodando para idx 215 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-The_LAO/moloch-4bc443f4dad60279b47978fc6987bb978d3dfc58/contracts/Moloch.sol
LLM: Reentrancy, Unprotected Ether Withdrawal, Integer Overflow/Underflow, Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence', 'SWC-105-Unprotected Ether Withdrawal', 'SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 216 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyWithdrawMinimizeTrading.sol
LLM: Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 217 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyPartialCloseLiquidate.sol
LLM: Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 218 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyPartialCloseMinimizeTrading.sol
LLM: Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 219 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyAddBaseTokenOnly.sol
LLM: Outdated Compiler Version, Transaction Order Dependence
GT: ['SWC-102-Outdated Compiler Version', 'SWC-114-Transaction Order Dependence']


--- Rodando para idx 220 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyAddTwoSidesOptimal.sol
LLM: Outdated Compiler Version
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 221 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/strategies/spookyswap/SpookySwapStrategyLiquidate.sol
LLM: Outdated Compiler Version, Potential Reentrancy, Infinite Approval
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 222 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-SpookySwap Integration & Fantom Expansion/bsc-alpaca-contract-4553a34a6dcfcfbf7aebc693bb5c5c6074c73129/contracts/6/protocol/workers/spookyswap/SpookyWorker03.sol
LLM: Reentrancy vulnerability, Transaction Order Dependence, Approval issues
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 223 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Coinfabrik-Beluga Pay (BBI) Security Audit/contractBBIT-master/bbi.sol
LLM: Integer Overflow and Unprotected Ether Withdrawal
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-105-Unprotected Ether Withdrawal']


--- Rodando para idx 224 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-88mph/88mph-contracts-76cd9d1fc45e65f5d0f686621fe6af85c40aa140/contracts/rewards/xMPH.sol
LLM: Unchecked Call Return Value, Potential Reentrancy
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 225 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Compound_Open_Oracle/open-oracle-e7a928334e5e454a88eec38e4ee1be5ee3b13f08/OpenOracleData.sol
LLM: Improper Signature Validation, Deprecated Solidity Version, Lack of Access Control
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 226 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Compound_Open_Oracle/open-oracle-e7a928334e5e454a88eec38e4ee1be5ee3b13f08/DelFiPrice.sol
LLM: SWC-108-State Variable Default Visibility
GT: ['SWC-108-State Variable Default Visibility']


--- Rodando para idx 227 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Zer0_zNS/zNS-b05e503ea1ee87dbe62b1d58426aaa518068e395/contracts/Registrar.sol
LLM: Reentrancy, Access Control Issues
GT: ['SWC-135-Code With No Effects', 'SWC-135-Code With No Effects']


--- Rodando para idx 228 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Zer0_zNS/zNS-b05e503ea1ee87dbe62b1d58426aaa518068e395/contracts/StakingController.sol
LLM: SWC-105, SWC-122, SWC-117
GT: ['SWC-105-Unprotected Ether Withdrawal', 'SWC-122-Lack of Proper Signature Verification', 'SWC-117-Signature Malleability']


--- Rodando para idx 229 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Inspex-Vault/aleswap-vault-efd3f777b2e9aaa2c635d3d0f463f1884e998112/contracts/strategies/Warden/StrategyWardenLP.sol
LLM: SWC-114-Transaction Order Dependence, SWC-132-Transaction Origin Vulnerability, SWC-20-Improper Access Control
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 230 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Frax/Frax.sol
LLM: DoS With Block Gas Limit
GT: ['SWC-128-DoS With Block Gas Limit']


--- Rodando para idx 231 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Frax/Pools/FraxPool.sol
LLM: Unchecked Call Return Value, Reentrancy Vulnerability, Access Control Issues
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 232 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Curve/CurveAMO.sol
LLM: Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 233 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Curve/CurveAMO_V2.sol
LLM: Integer Overflow and Reentrancy Risk
GT: ['SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 234 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-FraxFinance/frax-solidity-3f0993a70e3496fd27887db7754d68709c84015e/contracts/Misc_AMOs/InvestorAMO_V2.sol
LLM: Unchecked Call Return Value
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 235 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Coinbae-Barnbridge_Staking_Pool/Staking0xb0Fa2BeEe3Cf36a7Ac7E99B885b48538Ab364853/contracts/Staking.sol
LLM: Floating Pragma
GT: ['SWC-103-Floating Pragma']


--- Rodando para idx 236 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-COSMOS_Fundraiser/fundraiser-lib-693cf3f32e9fd679216372876dda86fa57a3277e/src/truffle/contracts/Fundraiser.sol
LLM: Integer Overflow and Underflow, Outdated Compiler Version, Reentrancy
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-102-Outdated Compiler Version', 'SWC-107-Reentrancy']


--- Rodando para idx 237 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Iosiro-Timvi Governance Token and Distribution DAO Smart Contract Audit/Timvi-Governance-a6e5929701b5da5ef9980b668216410245da59b7/Distribution.sol
LLM: Use of Deprecated Solidity Functions, Integer Overflow and Underflow
GT: ['SWC-111-Use of Deprecated Solidity Functions', 'SWC-111-Use of Deprecated Solidity Functions', 'SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 238 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Ackee_Blockchain-GoodGhosting/goodghosting-protocol-v1-dfda8d5d5990abb7f352bc9358ac950dce1bd677/goodghosting-protocol-v1-dfda8d5d5990abb7f352bc9358ac950dce1bd677/contracts/GoodGhosting.sol
LLM: Outdated Compiler Version, Potential Reentrancy Vulnerability, Incorrect Handling of Incentive Tokens
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 239 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-COIN98/code/code.sol
LLM: Reentrancy
GT: ['SWC-107-Reentrancy']


--- Rodando para idx 240 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Smartdec-Boomstarter Smart Contracts Security Review/boomstarter-ico-ec2d28f0c3243b8f782cbd44522b5a9ca0fc22a8/contracts/BoomstarterICO.sol
LLM: SWC-125, SWC-135
GT: ['SWC-125-Incorrect Inheritance Order', 'SWC-135-Code With No Effects']


--- Rodando para idx 241 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Solidified-2Key [14.10.2019]/contracts-de171eb80e9ce1c6566a5d782f0a0549ab0151ad/contracts/2key/singleton-contracts/TwoKeyMaintainersRegistry.sol
LLM: Gas limit vulnerability, Access control issue
GT: ['SWC-128-DoS With Block Gas Limit', 'SWC-128-DoS With Block Gas Limit']


--- Rodando para idx 242 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/SlowMist-wault.finance(WUSD) Smart Contract Security Audit Report/WUSD-91c541c2f1c0ac781ddcfb2be6a62555a5e1e8d1/WUSDMaster.sol
LLM: SWC-114-Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 243 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/PeckShield-BNPL/BNPL-0ee587a081668dcab166a3a275b8a6c4794ead4d/contracts/BankingNode.sol
LLM: Transaction Order Dependence, Reentrancy
GT: ['SWC-114-Transaction Order Dependence', 'SWC-107-Reentrancy']


--- Rodando para idx 244 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsecurity-Oasis  Multiply Smart Contracts/multiply-proxy-actions-e277ac1471a95138aaa93b39cf2c16c36c769740/contracts/multiply/MultiplyProxyActions.sol
LLM: Integer Overflow and Unchecked Call Return Value
GT: ['SWC-101-Integer Overflow and Underflow', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 245 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-SpiritSwap-SpiritSwap/spiritswap-core-a23463f87fd3c7633e97fab5e8124b4499e1519e/SpiritRouter.sol
LLM: Reentrancy vulnerability, use of assert statements
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 246 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-CryptoBatz Smart Contract/crypto-batz-contracts-07ee07dd442c34622798f1ee5b73ef8ff59cef48/contracts/CryptoBatz.sol
LLM: Reentrancy, Timestamp Manipulation, Overflow
GT: ['SWC-116-Block values as a proxy for time']


--- Rodando para idx 247 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Fuel_Token/FUEL-Contracts-3717b751bb2fa57ae300776a93ee4d7d7beb2c07/FuelToken.sol
LLM: Fallback function vulnerability and upgrade risk
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 248 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/openzeppelin-Fuel_Token/FUEL-Contracts-3717b751bb2fa57ae300776a93ee4d7d7beb2c07/FuelCrowdfund.sol
LLM: SWC-112-Delegatecall to Untrusted Callee
GT: ['SWC-104-Unchecked Call Return Value']


--- Rodando para idx 249 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/Staking.sol
LLM: Integer Overflow and Underflow
GT: ['SWC-135-Code With No Effects']


--- Rodando para idx 250 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/staking_pools/MixinStakingPool.sol
LLM: SWC-116-Block values as a proxy for time
GT: ['SWC-112-Delegatecall to Untrusted Callee']


--- Rodando para idx 251 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/libs/LibFixedMath.sol
LLM: SWC-135-Code With No Effects
GT: ['SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 252 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/sys/MixinScheduler.sol
LLM: Division by zero
GT: ['SWC-116-Block values as a proxy for time']


--- Rodando para idx 253 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/staking/contracts/src/interfaces/IStructs.sol
LLM: Reentrancy, Deprecated Function, Integer Overflow/Underflow
GT: ['SWC-135-Code With No Effects', 'SWC-135-Code With No Effects']


--- Rodando para idx 254 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-0x_v3_Staking/0x-monorepo-b8e01d7be535196a3145a431291183ecfbb333c6/contracts/dev-utils/contracts/src/LibAssetData.sol
LLM: Unchecked Call Return Value
GT: ['SWC-119-Shadowing State Variables']


--- Rodando para idx 255 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-origin/origin-4b31657825523962434c6d4e4c61feb0bb1ee518/origin-contracts/contracts/marketplace/v00/Marketplace.sol
LLM: Integer Overflow and Underflow, Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 256 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Hacken-TrustSwap-V1/code/StakingPool.sol
LLM: Transaction Order Dependence
GT: ['SWC-104-Unchecked Call Return Value', 'SWC-104-Unchecked Call Return Value']


--- Rodando para idx 257 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-hermez/contracts-d52ed73a0c7deaf06fcb0f981e14326f95cd1b78/contracts/auction/HermezAuctionProtocol.sol
LLM: Reentrancy, Transaction Order Dependence
GT: ['SWC-114-Transaction Order Dependence', 'SWC-101-Integer Overflow and Underflow', 'SWC-101-Integer Overflow and Underflow', 'SWC-101-Integer Overflow and Underflow']


--- Rodando para idx 258 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-hermez/contracts-d52ed73a0c7deaf06fcb0f981e14326f95cd1b78/contracts/withdrawalDelayer/WithdrawalDelayer.sol
LLM: Logic Error
GT: ['SWC-114-Transaction Order Dependence']


--- Rodando para idx 259 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Trail_of_Bits-hermez/contracts-d52ed73a0c7deaf06fcb0f981e14326f95cd1b78/contracts/hermez/Hermez.sol
LLM: Outdated Compiler Version, Reentrancy Vulnerability
GT: ['SWC-114-Transaction Order Dependence', 'SWC-107-Reentrancy']


--- Rodando para idx 260 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/Chainsulting-GSPI Club-project3/code/spi_staking.sol
LLM: Outdated Compiler Version, Block values as a proxy for time
GT: ['SWC-103-Floating Pragma', 'SWC-135-Code With No Effects']


--- Rodando para idx 261 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Paxos/simple-multisig-master/contracts/SimpleMultiSig.sol
LLM: Reentrancy vulnerability, improper state management
GT: ['SWC-102-Outdated Compiler Version']


--- Rodando para idx 262 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/QuillAudits-VIDB - v1.0/VIDBToken/VIDBToken.sol
LLM: Out-of-bounds access, potential reentrancy vulnerability
GT: ['SWC-102-Outdated Compiler Version', 'SWC-116-Block values as a proxy for time']


--- Rodando para idx 263 ---
File: DAppSCAN-main/DAppSCAN-source/contracts/consensys-Idle_Finance/idle-tranches-d94ee7194e8cb17db13b16c338f3e780b62f5435/contracts/IdleCDO.sol
LLM: Integer Overflow, Deprecated Functionality
GT: ['SWC-107-Reentrancy']


--- Rodando para idx 264 ---

In [15]:
comparison_results = []

for bug_pred, gt_cat in tqdm(zip(error_cases['bug_type'], gt_categories), total=len(gt_categories)):
    prompt = prompts.create_zeroshot_error_comparison_prompt(bug_pred, gt_cat)
    response = call_openai(MODEL_NAME, prompt)
    try:
        result = json.loads(response)
        same_error = int(result.get("same_error", False))
    except Exception as e:
        print("Erro ao interpretar resposta da LLM:", e)
        same_error = 0 

    comparison_results.append({'actual_has_error': 1, 'predicted_has_error': same_error})

comparison_df = pd.DataFrame(comparison_results)

precision, recall, f1, conf_matrix = evaluate_experiment(comparison_df)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")

  0%|          | 0/198 [00:00<?, ?it/s]

100%|██████████| 198/198 [03:25<00:00,  1.04s/it]

Precision: 100.00
Recall: 20.71
F1-Score: 34.31
Confusion Matrix:
[[  0   0]
 [157  41]]